### ISSUE TITLE
Unable to login to Docker Cloud

### ISSUE THREAD

**Issue by brandonroyal** [docker/for-mac#1919]
### Expected behavior
Docker Cloud login successful

### Actual behavior
Username & password not accepted.  Same username & password work on cloud.docker.com

### Information

![image](https://user-images.githubusercontent.com/2762697/28785954-a83e77d0-75cc-11e7-8a0f-97b95a55b622.png)

Docker for Mac: version: 17.07.0-ce-rc1-mac21 (69202b202f497d4b6e627c3370781b9e4b51ec78)
macOS: version 10.12.6 (build: 16G29)
logs: /tmp/9AB87EF1-064A-4372-BC82-11A4769FF023/20170731-083909.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

[logs.tar.gz](https://github.com/docker/for-mac/files/1188077/logs.tar.gz)

### Steps to reproduce the behavior

  1. Open Docker Cloud login dialog
  2. Login

**Comment by kradenkov** [comment]
I have the same problem with 17.06.0-ce-mac19 (18663) version.

**Comment by akilleen** [comment]
I am having the same issue on Version 17.06.0-ce-mac19 (18663) as well.

**Comment by akilleen** [comment]
To add some more info, it seems to be related to the password. If I have a password with special characters (!@#$%^&*:;'") it doesn't let me log in. If I change my password to a strictly alphanumeric one, it does work.

**Comment by kradenkov** [comment]
Version 17.06.1-ce-mac24 (18950) still have this defect

**Comment by JasonOffutt** [comment]
I ran into this issue on Version 17.06.2-ce-mac27 (19124). @akilleen's solution worked for me.

**Comment by john-k-ge** [comment]
I'm using `Version 17.06.2-ce-mac27 (19124)` with a pure alphanumeric password, and I can't logon  either.

**Comment by richtong** [comment]
Any fix time for this, it sure is frustrating and makes docker for Mac unusable for pushing etc.

**Comment by n4ss** [comment]
This issue is fixed in the latest release.

**Comment by george-freebirdrides** [comment]
Having the same issue, downloading the latest build on a fresh brand new MBP.

**Comment by n4ss** [comment]
@george-freebirdrides does the login work without a `:` character?

**Comment by rajdevireddy** [comment]
I still see this problem on Mac `Verison 10.13.2 (17C205)` and Docker version `Engine: 17.12.0-ce`. And I am unable to push images to docker hub. I did change my password to be alphanumeric with no special characters and can login to cloud.docker.com from a browser with that password.

This is what I see in the diagnosis tool:
```
Docker for Mac: version: 17.12.0-ce-mac49 (d1778b704353fa5b79142a2055a2c11c8b48a653)
macOS: version 10.13.2 (build: 17C205)
logs: /tmp/73D93342-838B-4BB6-B54F-0498C1A6BD9C/20180211-120814.tar.gz
[OK]     db.git
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk
```

And here is what I see in the mac console log (filter set to errors only) when I try to login:

<img width="1129" alt="docker-login-issue" src="https://user-images.githubusercontent.com/6588756/36076100-f7ea6ac6-0f25-11e8-9d5c-0c98f3d2cdd8.png">

These seems to be the problem (?)
```
loginwindow is not entitled
```
or

```
HttpClient: Failed to send request. An SSL error has occurred and a secure connection to the server cannot be made.
```

But I can not tell what that SSL error is. I am wondering if a security tool that monitors all connections in and out of my laptop is causing issues here. But I am not sure entirely. Any pointers to where I can find what this URL is that docker app tries to call for login auth and find what SSL certificates are on that URL or anyway to see more logs,  may be to print SSL handshake logs, would be of great help...

**Comment by prosegay** [comment]
I just downloaded and restarted with 18.03.0-ce, I can login to the docker gui but the same credentials do not work with cli: 'docker login'

**Comment by Algohash** [comment]
Hi,

I still have this problem. Mine is little bit unique, I guess.

1. I can login to hub.docker.com and cloud.docker.com from the browser.
2. I can login to Docker MAC (Version 18.03.1-ce-mac65 (24312) ) from my personal MAC laptop.
3. However, I cannot login to Docker MAC from my office laptop. My password is alphanumeric.

I'm not sure what is happening here? Any help?

**Comment by JoshVazq** [comment]
@Algohash Same scenario.
Version 18.03.1-ce-mac65 (24312)
OSX 10.13.5 (17F77)
1. I can login through browser.
2. I cannot login (both from Docker icon in task menu and from CLi)

**Comment by inaw-tihor** [comment]
@JoshVazq and @Algohash i am also facing the same issue. 
Version 18.03.1-ce-mac65 (24312)
OSX 10.13.5 (17F77)

Any resolution of this.

**Comment by n4ss** [comment]
@JoshVazq @inaw-tihor @carmenandreia Do you have the right binary at `/usr/local/bin/docker-credential-osxkeychain` ? The alphanumeric password issue has been fixed for a long time.

**Comment by dshamanthreddy** [comment]
I have same isuue 
I can login through browser.
I can't login (both from Docker icon in mac

**Comment by LeMueller** [comment]
I have the same problem on Windows10 version

**Comment by greygatch** [comment]
Still an issue. Can log into the web application, but not through the GUI.

**Comment by itakanata** [comment]
I had same issue.
And now works fine.
I tried not to use capital letters in passwords.

Version 18.06.1-ce-mac73
OS X 10.14

**Comment by RaveenBouy** [comment]
Can't believe that this problem isn't resolved yet... how hard is it to change some codes...

**Comment by jamiehicks154** [comment]
login button on GUI on mac osx in disabled? 
![Screenshot 2019-08-29 at 11 40 02](https://user-images.githubusercontent.com/41266385/63933776-c8b55700-ca51-11e9-9f30-7d165d0c0f3e.png)
