### ISSUE TITLE
Seeing random disconnects from running container: "connect: connection refused"

### ISSUE THREAD

**Issue by tim-ireland** [docker/for-mac#196]
### Expected behavior

Container to stay up until explicitly torn down.

### Actual behavior

Container seems to crash randomly

### Information

My build starts a docker container with the following run command:

```Shell
docker run -it -e $ENV_VAR -p $PORT1 -p $PORT2 -p $PORT3 --name=$NAME -v $MOUNT1 -v $MOUNT2 -v $MOUNT3 -v $MOUNT4 IMAGE "$@"
```

Seeing the following error frequently.  In my case it seems that randomly a running container becomes unavailable.  

I saw the same behavior last week, and tried an uninstall/reset which seemed to correct the issue for a day or two.   Now after a few days the behavior is back.  Laptop did sleep in between, but the failing container was recreated from scratch this morning.

```
[root@30a535b14bc0 ~]# Error response from daemon: dial unix /Users/XXX/Library/Containers/com.docker.docker/Data/*00000003.00000948: connect: connection refused
```

I usually have a second connection to the container for debugging, started via `docker exec -it 30a535b14bc0 bash`

Docker is currently provided 4GB RAM and 4 CPUs.

### Diagnostics:

```
Diagnostic ID: 907F5E9D-5863-464E-BF60-5A67E20E9EEE
Docker for Mac: 1.12.0 (Build 10871)
macOS: Version 10.11.5 (Build 15F34)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux
```

```
# docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 29
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 21
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge overlay null host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.856 GiB
Name: moby
ID: 2YKL:C6DJ:EI3P:PF76:X532:VSVK:SRHX:43S2:SSME:KXBU:TJMQ:QYQK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 16
 Goroutines: 28
 System Time: 2016-08-09T17:48:45.075345775Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

### Steps to reproduce

In One case:

1. Create Docker instance, mounting a directory that is tracked by a git repo inside the container.
2. Make changes to said source code, in my case the changes were to config files. 
3. From git outside of docker (SourceTree for example) ignore changes to the file.

Not always reproducible.

**Comment by tim-ireland** [comment]
Corresponding log messages immediately after failure `/Users/timireland/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/syslog`:

```
2016-08-09 20:15:28 +0000 UTC daemon.crit /sbin/transfused: read /host_docker_app: EOF reading length
2016-08-09 20:15:29 +0000 UTC daemon.error acpid: PWRF/00000080
2016-08-09 20:15:29 +0000 UTC daemon.info init: starting pid 19404, tty '': '/sbin/openrc shutdown'
```

**Comment by dsheets** [comment]
We believe this issue has been fixed in Beta 22 and will reach stable 1.12.1 in a few weeks.

**Comment by dsheets** [comment]
Sorry, I got confused. This will be fixed in the upcoming Beta 23.

**Comment by dsheets** [comment]
Beta 23 has now been released which should fix this issue. This fix should reach the stable channel with 1.12.1 in a few weeks. If the problem persists, please re-open this issue.

Thanks for your help making Docker for Mac better!

**Comment by roks0n** [comment]
I upgraded to Beta 23 and am still experiencing this issues.

![image](https://cloud.githubusercontent.com/assets/889696/17785824/8fdd2b6a-6582-11e6-9881-d326e0136207.png)

**Comment by dsheets** [comment]
@roks0n there are many possible causes for this symptom. @tim-ireland's specific issue was fixed but I cannot tell if your issue is the same and the fix that went out in Beta 23 should be applicable. Please use the "Diagnose & Feedback" menu item from 🐳 to post an issue with your diagnostic ID. Thanks for your report!

**Comment by tim-ireland** [comment]
I took the update to Version 1.12.0-a (build: 11213) and it seems stable for the last few days.
