### ISSUE TITLE
SRV record lookups fail when using docker-compose

### ISSUE THREAD

**Issue by bkad** [docker/for-mac#209]
### Expected behavior
SRV record lookups should work in docker-compose

### Actual behavior
SRV record lookups fail in docker-compose. Curiously they still work when I run them through docker rather than docker-compose.

### Information

Diagnostic ID: 5DF41E89-0B59-48B6-9746-7CB394B5BC2D
Docker for Mac: 1.12.0-beta21 (Build 11019)
macOS: Version 10.11.6 (Build 15G31)
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

docker-compose.yml:

```yaml
version: '2'
services:
  srv:
    image: ubuntu
```

### Steps to reproduce

1. `docker-compose run srv /bin/bash -c "apt-get update; apt-get install -y dnsutils; host -t SRV _kerberos._udp.ox.ac.uk"`
2. See the error: `_kerberos._udp.ox.ac.uk has no SRV record`

Note that running `docker run --rm -it ubuntu /bin/bash -c "apt-get update; apt-get install -y dnsutils; host -t SRV _kerberos._udp.ox.ac.uk"` still works.

This is causing issues with my VPN workflow in the office where my compose container can't access the company package index.

I believe this is a regression as well, it was working at some point during the Docker-For-Mac beta.

**Comment by dsheets** [comment]
Original forum report at <https://forums.docker.com/t/srv-record-lookups-fail-when-using-docker-compose/18228>.

**Comment by djs55** [comment]
The key difference appears to be that `docker-compose` creates a network `compose_default` with the docker embedded DNS server enabled, to allow one container to look up the name of another.

On `compose_default` with the embedded server in 1.12.0 I see the failure:
```
$ docker run --rm -it --network compose_default compose_srv /bin/bash -c "host -t SRV _kerberos._udp.ox.ac.uk"
_kerberos._udp.ox.ac.uk has no SRV record
```
while it works on the default network:
```
$ docker run --rm -it --network default compose_srv /bin/bash -c "host -t SRV _kerberos._udp.ox.ac.uk"
_kerberos._udp.ox.ac.uk has SRV record 0 0 88 kdc0.ox.ac.uk.
_kerberos._udp.ox.ac.uk has SRV record 0 0 88 kdc1.ox.ac.uk.
_kerberos._udp.ox.ac.uk has SRV record 0 0 88 kdc2.ox.ac.uk.
_kerberos._udp.ox.ac.uk has SRV record 0 0 88 kdc3.ox.ac.uk.
```
After upgrading my docker daemon to 1.12.1 it's now working for me:
```
$ docker run --rm -it --network compose_default compose_srv /bin/bash -c "host -t SRV _kerberos._udp.ox.ac.uk"
_kerberos._udp.ox.ac.uk has SRV record 0 0 88 kdc0.ox.ac.uk.
_kerberos._udp.ox.ac.uk has SRV record 0 0 88 kdc1.ox.ac.uk.
_kerberos._udp.ox.ac.uk has SRV record 0 0 88 kdc2.ox.ac.uk.
_kerberos._udp.ox.ac.uk has SRV record 0 0 88 kdc3.ox.ac.uk.
```

So I think the root cause was a bug/limitation in the embedded DNS server, needed by `compose`. I believe it's fixed in 1.12.1.

The fix should be in the next beta update, due around 2016-08-23 (next tuesday)-- please try again then and let us know what happens!

**Comment by bkad** [comment]
Thanks for the diagnosis! I realize it isn't the 23rd yet, but I noticed the version I'm currently running is 1.12.1 so I figured I would give it a try. Unfortunately, still doesn't work. Is there a specific version/build number for 1.12.1 I should be looking for? More detailed version info:

```
Version 1.12.1-rc1-beta23 (build: 11375)
2f0427ac7d4d47c705934ae141c3a248ed7fff40
```

**Comment by bkad** [comment]
Just got the latest release (Version 1.12.1-beta24 (build: 11508)) and everything is working now, thanks!
