### ISSUE TITLE
File-Event propagation stopping (worse in current stable/edge)

### ISSUE THREAD

**Issue by EugenMayer** [docker/for-mac#2417]
I am maintaining http://docker-sync.io where we try to overcome some effects host-mounts in d4m ( docker on OSX in general ) spawn, specifically the performance.

We offer different ways ( rsync, unison ) and since about 1 year, OSXFS based "native_osx" - this relys on the FS events propagated by d4m - please see the chart here https://github.com/EugenMayer/docker-sync/wiki/8.-Strategies#native_osx-osx

a) It is known, that the propagation does stop working after some time, even before mac42: https://github.com/EugenMayer/docker-sync/issues/410 - the only way we fix that is by restarting d4m completely - are there any better ways to that?

b) (the actual reason for this issue, but related to a) Now, since 42+ ( 42 works well ) things got a lot worse, that said, FS even propagation stops after some few operations or just some time, see https://github.com/EugenMayer/docker-sync/issues/517

People do downgrade to mac42 https://github.com/EugenMayer/docker-sync/issues/517#issuecomment-356716739 and seem to have far better results

Referencing to your statement
```
Volumes shared from the host are mounted remotely using a protocol that is quite similar to NFS, extended with support for transporting filesystem events. 
```

a) can we "restart" that service, when it stuck? Without restarting all containers
b) can we fix FS system propagation?
c) can we somehow detect when FS propagation has been stuck ( to trigger a )

Thanks

**Comment by djs55** [comment]
Thanks for the ticket -- I'm hoping to investigate event propagation soon.

**Comment by pkyeck** [comment]
I don't get any `inotify` events anymore - is this related?

**Comment by EugenMayer** [comment]
@pkyeck yes, thats exactly the point. Those inotify events are not triggering and since we use unison to sync, that one is not triggered ( and you might use the usual node tooling watch tasks failing the same way )

**Comment by adiq** [comment]
Any updates on this one? I guess this is a serious problem that should be resolved as soon as possible. If there is no time, the mount protocol should be reverted to old one.

**Comment by EugenMayer** [comment]
An update here, mac55 with the fallback to raw did not help with this issue, this makes it clear, that those issues have rather to do with the new linux-distro from +42 and maybe specific ulimit/sysctl values which are now to limiting?

At least, wanting to share that mac55 is no fix for that one, since this issue is on High Sierra and Sierra, APFS and non APFS

**Comment by nazar** [comment]
Any updates on this issue? This is a blocker for those of us developing inside docker containers in macos to upgrade beyond 17.09 due to the broken inotify issues reported here.

**Comment by nazar** [comment]
Thanks for the info @baohx2000 - I did try using the unison strategy via the excellent [docker-sync](https://github.com/EugenMayer/docker-sync) but the experience was less than ideal: it took a while to install on macos and CPU usage was much higher - so much so that it wasn't a usable solution for us.

Currently the perfect solution in terms of ease of setup and IO performance is using `docker 17.09-mac-42` with `docker-sync` with the `native_osx` strategy. The only issue is that breaks when updating docker beyond `docker 17.09-mac-42` and thus isn't a solution I can recommend to our development team.

**Comment by EugenMayer** [comment]
@nazar @baohx2000 to clarify, that CPU usage does not come from unison, but from unox, the file watcher which triggers unison - but you need that one to run unison on OSX - that is exactly why native_osx has been created, to avoid any file watch on OSX since they all are fairly bad in performance due to the FS-Layer having aweful events.

**Comment by jak** [comment]
We're really struggling with this. Is there a known combination that works, using anything newer than 17.09? 

Is there anything we can do to help provide additional data? We have a couple of mac's we can test on.

**Comment by djs55** [comment]
I discovered one possible way the event stream from `osxfs` could fail -- the fix is in the latest edge [18.05.0-ce-rc1-mac63](https://download.docker.com/mac/edge/24246/Docker.dmg) released today. If you get a chance to try it let me know if it's any better. Thanks for your patience!

**Comment by jak** [comment]
@djs55 Thanks. Installed on two developer macbooks and first impressions from both devs are that it's better, i.e. no fs events have stopped. I will report back after some more intensive use.

**Comment by jak** [comment]
@djs55 Unfortunately I have a report from a dev on the my team of the fs events stopping again, after a few hours use on the mac63 release. A restart hasn't helped. This is a new touchbar model with APFS (though [earlier comments indicate this isn't a factor](https://github.com/docker/for-mac/issues/2417#issuecomment-371517445)), with a qcow image.

Truly appreciate the effort.

**Comment by wesselvdv** [comment]
@djs55 I have been running this for a whole day on my mid-2015 MBP. No issues yet, running with a .raw image though.

**Comment by fdanielsen** [comment]
I just want to chime in here guys with a reference to #2375. Since getting my new MBP running with APFS, I haven't felt the need for docker-sync with respect to speed, but I have a somewhat weird issue of some containers seemingly receiving notification of changes to files and others not. Eg. my Python containers notice changes to Python files, while my Webpack devserver container doesn't notice changes to any source files (JS, SCSS mainly). I wouldn't doubt that's because of different container images (and OSes) or possibly different file system watch strategies, but…

In the comments to the aforementioned issue there was an interesting note of starting a separate container with `docker run -v source-dir:container-dir …` mounting the same directory into the container as used in Kubernetes. I tried that (in my case together with a compose file stack), and suddenly file system events where propagating into the Webpack devserver container too. Nothing but starting that extra container separately "solved" it. Quite annoying, but better than manually triggering file changes within the container.

Also running .raw image, on macOS 10.13.4 with APFS and Docker 18.05.0-ce-rc1-mac63 (24246).

**Comment by michalkleiner** [comment]
@fdanielsen interesting. What file editor you're using to edit the js and scss files? There's a thing with Sublime and maybe Atom (and potentially other file editors) where they do not save files immediately and therefore the event can't occur. Not sure how a separate container would fix this though.

**Comment by fdanielsen** [comment]
@michalkleiner I'm using vim. I read in Webpack's documentation that the `backupcopy` setting might  affect its ability to pick up changes, and tried setting it to `backupcopy=yes` as suggested but without anything happening. I also of course use the exact same editor to edit my Python files.

**Comment by anveo** [comment]
We are experiencing the same issue as @fdanielsen. Most projects appear to propagate filesystem changes fine, but a large ember project (~100k files in node_modules) consistently fails to pick up file changes. Recently a few developers have also reported issues with a smaller create-react-app based project. The ember app is not running along side in that case. Edge build 18.05.0-ce-rc1-mac63 doesn't appear to have fixed the problem.

**Comment by adiq** [comment]
@djs55 I am using edge version and hasn't experienced issues yet with docker-sync. I'll try to update again on this issue after a longer period of time. I do not use dummy-container workaround.

**Comment by EugenMayer** [comment]
@djs55 we have quiet some testing on docker-sync with edge63 right now. Results are basically

a) its better then anything after mac42 stable - but its worse then mac42 (significantly)
b) qcow based mac63 edge is useless - entirely broken when looking on FS events
c) mac63edge + raw is kind of something, but i would by no means advice to upgrade from 42 to edge63 - its really still a lot worse

You can see the test results and scenarios here https://github.com/EugenMayer/docker-sync/issues/517#issuecomment-384874530 - several people have been testing it.

Hope that helps to at least mark the progress. I am really looking forward to see a progress here :)

**Comment by Kocicak** [comment]
Have you tried NFS share? It is similar setup like docker-sync (using an extra volume), but synchronization is done by NFS in macOS. This link helps setting it up: https://medium.com/@sean.handley/how-to-set-up-docker-for-mac-with-native-nfs-145151458adc

Our benchmark shows significant performance boost comparing to :cached (nfs 40ms vs cached 150ms response time), but it is done on very small php project. Haven't tried it on larger-scale projects.

**Comment by joar** [comment]
@fdanielsen 
> [...] Eg. my Python containers notice changes to Python files, while my Webpack devserver container doesn't notice changes to any source files (JS, SCSS mainly). I wouldn't doubt that's because of different container images (and OSes) or possibly different file system watch strategies, but…

If by "Python containers" you mean "Django runserver", it will be polling if `pyinotify` isn't installed.

You can check which file watch method your `runserver` is using by running
```python
import pyinotify
```
in a python process inside your container. Here's the Django source code for how `USE_INOTIFY` is set: https://github.com/django/django/blob/master/django/utils/autoreload.py#L56-L66.

**Comment by fdanielsen** [comment]
@joar Thanks for the info, but it's not Django. It is actually a container running uwsgi with `--py-autoreload` that runs a Flask app. It seems uwsgi uses polling by default too in this case, which would be why it works since it doesn't rely on file system events.

**Comment by dmitrif** [comment]
Any update on this by chance?

**Comment by ddanier** [comment]
Any update? This messes up any Magento 2.0 development on our side. Without docker-sync requests may take up to about 20 to 30 seconds. With docker-sync the same requests are finished in under 1 second. As docker-sync currently breaks after some time due to this d4m bug docker is not really usable here.

**Comment by knyttl** [comment]
Is it possible that this causes Java WatchService on FileSystem not seeing any changes in the mounted volumes? It works correctly on Linux. Any file change in mounted volume from the host system is ignored on OSX.

**Comment by EugenMayer** [comment]
@ddanier with the current edge, docker-sync is very stable, so you might go hat route again. its better since edge63

**Comment by EugenMayer** [comment]
@djs55 actually I did not try the stable ones from I think 63, since when it got fixed in stable.. those are great news!

**Comment by michalkleiner** [comment]
@djs55 how can one tell what code made it to stable and what's edge only?

**Comment by nazar** [comment]
@djs55 - I've updated to `Version 18.06.0-ce-mac70 (26399)` earlier this week. I'm on Sierra 10.12.6, using `qcow2` file and I've had zero issues with synching via `docker-sync`.

Thank you for the fix in stable - it's very much appreciated 👍

**Comment by EugenMayer** [comment]
Still closed / frozen?

**Comment by esetnik** [comment]
I'm still experiencing this issue as well. It should be reopened.

**Comment by nazar** [comment]
Same here. File propagation works well until a large number of files are updated on the HOST - i.e. I have to restart docker on High Sierra anytime I run `yarn install` in the project root.

**Comment by petkoneo** [comment]
We encountered this Issue and we came to a conclusion, that it is the issue with the docker dmg file and install process on docker website. If you use mac install the docker with: `brew cask install docker.` It will work afterwards. (For us it did.)

**Comment by michalkleiner** [comment]
@petkoneo are you suggesting that via brew the installation is somehow different to the dmg installation and one doesn't have file events propagation issues compared to the other? Can you reliably replicate that?

**Comment by petkoneo** [comment]
Yes but it is a suggestion. For now, we could resolve this problem on 2 computers. As far as I know the installation should be the same, but it still worked for us. (We were surprised as well) maybe it just needs a proper re-install.

**Comment by marbon87** [comment]
Reinstalling docker user brew cask didn't make a difference for me. Same problem :(

**Comment by daveisfera** [comment]
C18223FD-44DC-4ACD-B197-B660FC33917F/20191128104037

**Comment by daveisfera** [comment]
C18223FD-44DC-4ACD-B197-B660FC33917F/20200430200341

**Comment by michalkleiner** [comment]
@daveisfera what are these hashes for?

**Comment by daveisfera** [comment]
They're the id from when I uploaded the diagnostics when this error is happening

**Comment by daveisfera** [comment]
C18223FD-44DC-4ACD-B197-B660FC33917F/20200616212522
