### ISSUE TITLE
Severe Memory Leak on com.docker.vpn and high usage on com.docker.hyperkit

### ISSUE THREAD

**Issue by perrosc** [docker/for-mac#2780]
Please, check https://docs.docker.com/docker-for-mac/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have submitted Diagnostics
  - [x] I have included the Diagnostics ID in this Issue

### Expected behavior
Docker continues to run without consuming vast amounts of memory.
### Actual behavior
com.docker.vpn takes 13.37GB (yes thirteen) of memory
com.docker.hyperkit takes 1.80GB of memory
### Information

Diagnostic ID: F261E8D4-F645-4C2B-B0B4-6B5EA961C558

```
Docker for Mac: version: 18.03.0-ce-mac60 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
macOS: version 10.13.3 (build: 17D102)
logs: /tmp/F261E8D4-F645-4C2B-B0B4-6B5EA961C558/20180407-204919.tar.gz
[OK]     vpnkit
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     kubernetes
[OK]     files
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     disk
```

### Steps to reproduce the behavior

  1. Install docker on MacOS High Sierra
  2. Run Unifi and Watchtower containers:
```
docker run --name unifi -d \
    -p 3478:3478/udp -p 8080:8080 -p 8443:8443 \
    -p 8880:8880 -p 8843:8843 \
    -p 10001:10001/udp \
    -p 6789:6789 \
    -v /Volumes/Maple/unifi/certs:/usr/lib/unifi/cert  \
    -v /Volumes/Maple/unifi/data:/usr/lib/unifi/data  \
    -v /Volumes/Maple/unifi/logs:/usr/lib/unifi/logs \
    goofball222/unifi

docker run -d \
  --name watchtower \
  -v /var/run/docker.sock:/var/run/docker.sock \
  v2tec/watchtower
```
  3. Wait 47 hours (might happen sooner, but this is when I've noticed)
```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                                                                                                                                                      NAMES
7a0e5d492e10        v2tec/watchtower    "/watchtower"            47 hours ago        Up 47 hours                                                                                                                                                                                    watchtower
f19948c3b30f        goofball222/unifi   "docker-entrypoint.s…"   47 hours ago        Up 47 hours         0.0.0.0:6789->6789/tcp, 0.0.0.0:8080->8080/tcp, 0.0.0.0:8443->8443/tcp, 0.0.0.0:8843->8843/tcp, 0.0.0.0:3478->3478/udp, 0.0.0.0:10001->10001/udp, 0.0.0.0:8880->8880/tcp   unifi
```
 4. Check Activity Monitor

**Comment by logich** [comment]
I have had this with 3 simple web server containers consuming 63GB of memory if left running for a week. Containers are configured for Bridged network.

**Comment by jtownley** [comment]
I too am experiencing this as well. Running one small container launched via compose.
18.03.0-ce-mac60 (23751)
OSX 10.11.6 El Capitan

Fixed by reset. Uses about 24GB in 24hours

**Comment by amarshall** [comment]
Possibly related to https://github.com/moby/vpnkit/issues/371

**Comment by stephencelis** [comment]
Same. My memory's been swapping like crazy and I'm having to leave Docker closed most of the time.

**Comment by hourliert** [comment]
Same here:
Docker: 18.03.0-ce-mac60 (23751)
macOS: High Sierra 10.13.4

**Comment by michaelfresco** [comment]
I have the same issue on MacOS, High Sierra. (10.13.3)

**Comment by lapint** [comment]
I'm having the same problem on High Sierra

![image](https://user-images.githubusercontent.com/3252979/39533935-91cec7f8-4ded-11e8-8f05-2ec288a3a737.png)

**Comment by danielwelch** [comment]
Same issue on macOS High Sierra

**Comment by djs55** [comment]
Thanks for all your reports -- I'm investigating the issue.

There's a possibility that a memory leak exists in the new transparent HTTP proxy code.

In the [most recent build of the development branch](https://download-stage.docker.com/mac/bysha1/1529b8671a69476fd25467de8da7ce08dc96ba89/Docker.dmg) there is a switch to turn the transparent proxy on and off. If you install the build and then edit your `settings.json` file from a terminal:

```
jq .vpnKitTransparentProxy=false ~/Library/Group\ Containers/group.com.docker/settings.json > settings.json.2
mv settings.json.2 ~/Library/Group\ Containers/group.com.docker/settings.json
```

and then restart the app, the new setting should take effect.

Note that, in this configuration if you need to use an HTTP proxy for your containers then edit your $HOME/.docker/config.json and make it look something like this:

```
{
  "auths" : {

  },
  "proxies": {
    "default": {
      "httpProxy": "http://1.2.3.4:3128",
      "httpsProxy": "http://1.2.3.4:3128",
      "noProxy": "",
      "ftpProxy": ""
    }
  }
}
```

Let me know if this makes any difference.

**Comment by tempelkim** [comment]
Looks like it doesn't. :-(
Tried your suggestion with 18.05.0-ce-mac65 on 10.13.3. Within one hour of running two containers (postgres and nginx) it looks like this:

<img width="674" alt="vpnkit" src="https://user-images.githubusercontent.com/2526492/39919367-a973ac02-5513-11e8-9d9c-5686f115095b.png">

[10:50][ ~] % grep Transparent ~/Library/Group\ Containers/group.com.docker/settings.json
  "vpnKitTransparentProxy" : false

**Comment by djs55** [comment]
@tempelkim thanks for letting me know. That's quite a lot of memory usage within only one hour! I'm still having trouble reproducing it reliably-- could you describe your workload a little? Are you making requests to `nginx` from the outside over a forwarded port? If `nginx` is talking directly to `postgres` over the internal network then I think it shouldn't involve `com.docker.vpnkit`. In that case, do you know if anything is making external connections? You can have a look with

```
$ docker run -it --net=host -v `pwd`:/out alpine sh

/ # apk update && apk add tcpdump
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
v3.7.0-162-g06efc38960 [http://dl-cdn.alpinelinux.org/alpine/v3.7/main]
v3.7.0-161-gd98d33b7f4 [http://dl-cdn.alpinelinux.org/alpine/v3.7/community]
OK: 9050 distinct packages available
(1/2) Installing libpcap (1.8.1-r1)
(2/2) Installing tcpdump (4.9.2-r1)
Executing busybox-1.27.2-r7.trigger
tOK: 5 MiB in 13 packages

/ # tcpdump -s 0 -w /out/all.pcap -n -i eth0
tcpdump: listening on eth0, link-type EN10MB (Ethernet), capture size 262144 bytes
^C5692 packets captured
6300 packets received by filter
0 packets dropped by kernel
```
and then reading `all.pcap` with wireshark.

Thanks again for trying the transparent proxy change, sorry it didn't work :(

**Comment by tempelkim** [comment]
Postgres container is used by a Django Application under development (too much differences to sqlite, so I better use the real thing). That App runs outside Docker in a python3.6 virtual environment. Nginx is Proxy-Server for the Django App - so yes, we have requests from outside (be it localhost or some other machine). In this case (testing the REST-API) it was roundabout 30.000 requests to the API that caused the problem.

Out of curiosity it tried the same setup on a freshly installed Mac Pro (using 18.03.0) leading to exactly the same result.

**Comment by tempelkim** [comment]
...but it even keeps growing without any further requests. Left docker running over the weekend without any load at all on the containers and this is what I found this morning:

![dockermac](https://user-images.githubusercontent.com/2526492/39983187-14ccbab2-5757-11e8-87ef-e32718bfb34a.png)

**Comment by simonmallet** [comment]
I have the same problem with docker Version 18.03.1-ce-mac65 (24312)

It started happening max 2 weeks ago (possibly after I did an update to docker...)

It consumes between 5gb and 12gb generally.. To solve the problem I restart docker, but it comes back within one hour.

**Comment by simonmallet** [comment]
I downgraded to docker Version 17.12.0-ce-mac46 (21698) (January 2018) and I no longer have the memory leak issue.

**Comment by hourliert** [comment]
Where can we download the 17.12 version? I can't find it on the official website?

**Comment by simonmallet** [comment]
Right here :) https://docs.docker.com/docker-for-mac/release-notes/#docker-community-edition-17120-ce-mac55-2018-02-27

**Comment by hourliert** [comment]
Thanks a lot 👍

**Comment by djs55** [comment]
There's a candidate fix for this issue. If you'd like to try it before it gets officially released, there are instructions here: https://github.com/moby/vpnkit/issues/371#issuecomment-390248401

**Comment by simonmallet** [comment]
I'm trying it right now. Will let you know if it worked for me

**Comment by marcbachmann** [comment]
I just applied the fix yesterday. So far it's working for me. vpnkit is constantly at about 12MB.
Thanks for fixing this ❤️

**Comment by simonmallet** [comment]
Hello! The fix works for me as well. Usually by this time I had to restart Docker twice since the memory usage was above 5Gb... It hasn't gone beyond 110Mb in 5 hours 👍

**Comment by jasonrhaas** [comment]
Not sure if this should be closed.  Maybe its a different memory leak but I'm running 2.0.0.0-beta1-mac75 and seeing some serious memory usage starting at around 6 GB and going up to 20 GB.  This is even after shutting down all my containers.

**Comment by diranged** [comment]
I see this issue still on 18.06.. a fresh startup of Docker uses 4GB of ram within about 5 minutes of running. No containers at all.

![image](https://user-images.githubusercontent.com/768067/47589504-2c489280-d91e-11e8-8296-2e9407abccad.png)

**Comment by stephencelis** [comment]
When first reported I was seeing a leak that would take over 16GB+ of RAM. It's now stable at 4GB. Would definitely prefer it to be lower, though!

**Comment by diranged** [comment]
I have a hard time understanding how the thing can use 4GB of ram on a fresh startup at idle with no containers. Thats a bug, right?

**Comment by warden** [comment]
Same here after ~20s after startup of Docker.

<img width="553" alt="screenshot 2018-10-27 23 41 25" src="https://user-images.githubusercontent.com/521838/47609585-0e744e00-da42-11e8-9b13-75b7cb530795.png">
<img width="550" alt="screenshot 2018-10-27 23 41 35" src="https://user-images.githubusercontent.com/521838/47609586-13390200-da42-11e8-81f1-66d6b76e6f5b.png">

[Sample of com.docker.hyperkit.txt](https://github.com/docker/for-mac/files/2522223/Sample.of.com.docker.hyperkit.txt)

**Comment by jasonrhaas** [comment]
It looks like when docker starts up, it will immediate eat up the maximum amount of RAM that you allocated for it in your settings.  And then it just keeps creeping up from there.

**Comment by perrosc** [comment]
Ok, so it looks like the vpnkit leak is fixed, but the hyperkit memory usage is still high. I can reopen, and maybe @djs55 will decide to address here on in a separate issue.

**Comment by djs55** [comment]
When `hyperkit` starts it allocates virtual memory for the whole VM up-front. At this point no physical RAM is actually allocated but the allocation does appear as part of the "Virtual memory size" of `hyperkit`. Although this number looks large, it's really nothing to worry about since none of the memory is being used.

When Linux boots it starts writing to this memory (gradually). When Linux tries to write to a memory page, macOS will have to allocate it for real. I'm not 100% sure of the meanings of the categories in Activity Monitor but I suspect this will make it appear as part of the "Real Memory Size". If the page hasn't been written to for a while then macOS will write it to disk to free some RAM for some other tasks. I don't know if this would make "Real Memory Size" go down again.

So I would expect
- the Virtual Memory Size to remain large (and fairly constant). This should be related to the configured VM memory size + some smaller overheads of `hyperkit`
- the Real Memory Size to slowly increase, up to a maximum of the Virtual memory size
- unused memory to be swapped out to disk (or compressed), freeing space for other macOS programs.

If there is a memory leak in `hyperkit` the way to tell would be to plot a graph of the Virtual Memory Size, and show it increasing far beyond the configured VM memory size. I don't think we have any evidence of this *yet* -- I think what we're seeing in the screenshots above is expected as the VM boots.

**Comment by the-destro** [comment]
I think I can give you that evidence tomorrow. My work docker is using 32GB of RAM when it configured for only 16GB

**Comment by zapodot** [comment]
I still have this issue with the 2.2.0.3 release (Engine 19.03.5). Over time, the vpnkit-bridge will consumer increasingly more of my available RAM (32 GB). This in turn leads to MacOS starting to swap a lot and thus the machine becomes slow. Restarting docker fixes the problem. 
Note: I do not use a proxy for my containers

Output from running `top` for vpnkit-bridge process:

```
Processes: 529 total, 3 running, 526 sleeping, 3764 threads                                                                                                                                                                      08:35:06
Load Avg: 3.92, 4.66, 4.69  CPU usage: 8.64% user, 24.17% sys, 67.17% idle  SharedLibs: 238M resident, 64M data, 23M linkedit. MemRegions: 529363 total, 7065M resident, 127M private, 6564M shared.
PhysMem: 30G used (7330M wired), 1569M unused. VM: 3274G vsize, 1881M framework vsize, 1809449589(1905) swapins, 1830880562(338494) swapouts. Networks: packets: 66012509/40G in, 51032033/20G out.
Disks: 123386222/9099G read, 87722608/7774G written.

PID    COMMAND      %CPU TIME     #TH  #WQ  #POR MEM  PURG CMPR PGRP  PPID  STATE    BOOSTS    %CPU_ME %CPU_OTHRS UID  FAULTS   COW  MSGS MSGR SYSBSD     SYSM CSW        PAGE IDLEW POWE INSTRS    CYCLES    USER   #MRE RPRV VPRV VSIZ
40043  vpnkit-bridg 1.9  01:41:39 18   0    38   13G  0B   12G- 40039 40039 sleeping *0[1]     0.00000 0.00000    501  5492419+ 121  129  17   444859991+ 151  262406952+ 6    29841 1.9  24205214  72586593  sondre N/A  N/A  N
```

Output from running `top` for the com.docker.hyperkit process:
```
Processes: 531 total, 3 running, 528 sleeping, 3806 threads                                                                                                                                                                      08:39:50
Load Avg: 2.15, 3.46, 4.16  CPU usage: 11.30% user, 13.71% sys, 74.98% idle  SharedLibs: 239M resident, 65M data, 23M linkedit. MemRegions: 531338 total, 8627M resident, 132M private, 6674M shared.
PhysMem: 29G used (7418M wired), 3535M unused. VM: 3290G vsize, 1881M framework vsize, 1810605225(759) swapins, 1832958524(0) swapouts.  Networks: packets: 66018992/40G in, 51036396/20G out.
Disks: 123418013/9104G read, 87766377/7782G written.

PID    COMMAND      %CPU  TIME     #TH  #WQ  #POR MEM    PURG CMPR PGRP  PPID  STATE   BOOSTS    %CPU_ME %CPU_OTHRS UID  FAULTS   COW  MSGS MSGR SYSBSD      SYSM CSW        PAGE IDLEW    POWER INSTRS     CYCLES     USER   #MRE RPRV
40053  com.docker.h 134.4 46:55:30 17/3 0    40   7378M  0B   404M 40039 40044 running *0[1]     0.00000 0.00000    501  2272053  439  3187 178  1701587576+ 336  962007711+ 305  13828781 134.4 6711973142 5031566302 sondre N/A  N/A

```

**Comment by kaapplause** [comment]
Today I noticed the same problem - vpnkit-bridge use over 12GB
Docker version: 19.03.5
MacOS 10.15.2
