### ISSUE TITLE
Docker crash:  panic: runtime error: invalid memory address or nil pointer dereference - signal SIGSEGV

### ISSUE THREAD

**Issue by wyspaw** [docker/for-mac#3370]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: B703F310-95D2-4CE7-89DE-8DE7616361A9/20181127062759

### Expected behavior
Docker runs in a stable manner.

### Actual behavior
When running a container, Docker randomly crashes inside the virtual machine with a segmentation violation.
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x128 pc=0x4e23900]
```

### Information

  - macOS Version: 10.13.6 (17G65)

This occurs on multiple machines, all running the same version of Docker and macOS.
The issue is hard to reproduce, as it occurs at random and quite seldom on a single machine. However, I am working with about 50 macs and I face this crash about once per day on one of them.
The issue started after upgrade from 17.12.0 to 18.06.1.

### Diagnostic logs

```
Docker for Mac: version 18.06.1-ce-mac73 (26764)
Diagnose succeded.
```
All the crashes have the following snippet from the diagnostic logs in common:
```
018-11-26 22:07:31.956138+0100  localhost com.docker.hyperkit[30264]: time="2018-11-26T21:07:31.980115390Z" level=debug msg="Client context cancelled, stop sending events"
2018-11-26 22:07:31.989797+0100  localhost com.docker.supervisor[30196]: cannot read stdout from com.docker.driver.amd64-linux (pid: 30255): EOF
2018-11-26 22:07:31.992476+0100  localhost com.docker.supervisor[30196]: com.docker.driver.amd64-linux (pid: 30255): stderr: panic: runtime error: invalid memory address or nil pointer dereference
2018-11-26 22:07:31.993424+0100  localhost com.docker.supervisor[30196]: com.docker.driver.amd64-linux (pid: 30255): stderr: [signal SIGSEGV: segmentation violation code=0x1 addr=0x128 pc=0x4e23900]
2018-11-26 22:07:31.993447+0100  localhost com.docker.supervisor[30196]: com.docker.driver.amd64-linux (pid: 30255): stderr:
2018-11-26 22:07:31.993456+0100  localhost com.docker.supervisor[30196]: com.docker.driver.amd64-linux (pid: 30255): stderr: goroutine 10 [running]:
2018-11-26 22:07:31.993478+0100  localhost com.docker.supervisor[30196]: com.docker.driver.amd64-linux (pid: 30255): stderr: main.add(0x5302a40, 0xc4200bcb80, 0x53085c0, 0xc42007e000, 0xc420266080, 0xc42039c8c0, 0x40)
2018-11-26 22:07:31.993513+0100  localhost com.docker.supervisor[30196]: com.docker.driver.amd64-linux (pid: 30255): stderr:    /Users/administrator/jenkins/workspace/-macos-build_stable-18.06.x-GK5S6N46GBWZOV2D6MCUFEWYNRT7ZRYY2B4TYUK3GKXF6DLSJGHQ/src/github.com/docker/pinata/mac/backend/cmd/com.docker.driver.amd64-linux/events.go:78 +0xf0
2018-11-26 22:07:31.993540+0100  localhost com.docker.supervisor[30196]: com.docker.driver.amd64-linux (pid: 30255): stderr: main.watch(0x53085c0, 0xc42007e000, 0xc420266080, 0x0, 0x0)
2018-11-26 22:07:31.993549+0100  localhost com.docker.supervisor[30196]: com.docker.driver.amd64-linux (pid: 30255): stderr:    /Users/administrator/jenkins/workspace/-macos-build_stable-18.06.x-GK5S6N46GBWZOV2D6MCUFEWYNRT7ZRYY2B4TYUK3GKXF6DLSJGHQ/src/github.com/docker/pinata/mac/backend/cmd/com.docker.driver.amd64-linux/events.go:53 +0x4a3
2018-11-26 22:07:31.993558+0100  localhost com.docker.supervisor[30196]: com.docker.driver.amd64-linux (pid: 30255): stderr: main.startWatchingEvents(0x53085c0, 0xc42007e000, 0x0, 0x0)
2018-11-26 22:07:31.993566+0100  localhost com.docker.supervisor[30196]: com.docker.driver.amd64-linux (pid: 30255): stderr:    /Users/administrator/jenkins/workspace/-macos-build_stable-18.06.x-GK5S6N46GBWZOV2D6MCUFEWYNRT7ZRYY2B4TYUK3GKXF6DLSJGHQ/src/github.com/docker/pinata/mac/backend/cmd/com.docker.driver.amd64-linux/events.go:33 +0x17b
2018-11-26 22:07:31.993575+0100  localhost com.docker.supervisor[30196]: com.docker.driver.amd64-linux (pid: 30255): stderr: main.run.func2(0xc4202e6000)
2018-11-26 22:07:31.993582+0100  localhost com.docker.supervisor[30196]: com.docker.driver.amd64-linux (pid: 30255): stderr:    /Users/administrator/jenkins/workspace/-macos-build_stable-18.06.x-GK5S6N46GBWZOV2D6MCUFEWYNRT7ZRYY2B4TYUK3GKXF6DLSJGHQ/src/github.com/docker/pinata/mac/backend/cmd/com.docker.driver.amd64-linux/main.go:95 +0x2b
2018-11-26 22:07:31.993591+0100  localhost com.docker.supervisor[30196]: com.docker.driver.amd64-linux (pid: 30255): stderr: created by main.run
2018-11-26 22:07:31.993601+0100  localhost com.docker.supervisor[30196]: com.docker.driver.amd64-linux (pid: 30255): stderr:    /Users/administrator/jenkins/workspace/-macos-build_stable-18.06.x-GK5S6N46GBWZOV2D6MCUFEWYNRT7ZRYY2B4TYUK3GKXF6DLSJGHQ/src/github.com/docker/pinata/mac/backend/cmd/com.docker.driver.amd64-linux/main.go:94 +0x1e7
2018-11-26 22:07:31.993616+0100  localhost com.docker.supervisor[30196]: cannot read stderr from com.docker.driver.amd64-linux (pid: 30255): EOF
2018-11-26 22:07:31.997519+0100  localhost com.docker.supervisor[30196]: Reap com.docker.driver.amd64-linux (pid: 30255): exit status 2
2018-11-26 22:07:32.003178+0100  localhost com.docker.supervisor[30196]: Stop 1 children with order 1: [com.docker.driver.amd64-linux (pid: 30255)]
2018-11-26 22:07:32.003225+0100  localhost com.docker.supervisor[30196]: Supervisor caught an error
2018-11-26 22:07:32.005440+0100  localhost com.docker.supervisor[30196]: StopAll
2018-11-26 22:07:32.005516+0100  localhost com.docker.supervisor[30196]: Stop 2 children with order 2: [com.docker.osxfs (pid: 30253) com.docker.vpnkit (pid: 30254)]
2018-11-26 22:07:32.005548+0100  localhost com.docker.supervisor[30196]: Send signal terminated to com.docker.osxfs (pid: 30253)
2018-11-26 22:07:32.005603+0100  localhost com.docker.supervisor[30196]: Send signal terminated to com.docker.vpnkit (pid: 30254)
2018-11-26 22:07:32.006923+0100  localhost com.docker.hyperkit[30264]: time="2018-11-26T21:07:32.030057866Z" level=debug msg="container mounted via layerStore: &{/var/lib/docker/overlay2/24f3227317388805e1a175af9b8657e4295842823f76ec35adf72d3da77b5316/merged 0x31e8680 0x31e8680}"
2018-11-26 22:07:32.009271+0100  localhost com.docker.supervisor[30196]: cannot read stderr from com.docker.osxfs (pid: 30253): EOF
2018-11-26 22:07:32.009287+0100  localhost com.docker.supervisor[30196]: cannot read stdout from com.docker.osxfs (pid: 30253): EOF
2018-11-26 22:07:32.010009+0100  localhost com.docker.hyperkit[30264]: [570339.948194] transfused[1242]: segfault at 7fed2f4c2f48 ip 00007fed2f3d4e1f sp 00007fed2f4c2f50 error 6 in transfused[7fed2f3ce000+11000]
2018-11-26 22:07:32.012644+0100  localhost com.docker.supervisor[30196]: Reap com.docker.osxfs (pid: 30253): signal: terminated
2018-11-26 22:07:32.016484+0100  localhost com.docker.supervisor[30196]: cannot read stderr from com.docker.vpnkit (pid: 30254): EOF
2018-11-26 22:07:32.016515+0100  localhost com.docker.supervisor[30196]: cannot read stdout from com.docker.vpnkit (pid: 30254): EOF
2018-11-26 22:07:32.016644+0100  localhost com.docker.supervisor[30196]: Reap com.docker.vpnkit (pid: 30254): signal: terminated
2018-11-26 22:07:32.110007+0100  localhost com.docker.supervisor[30196]: Supervisor has failed, shutting down: Supervisor caught an error: one of the children died: com.docker.driver.amd64-linux (pid: 30255)
2018-11-26 22:07:32.358780+0100  localhost docker[40933]: (libsystem_info.dylib) Created Activity ID: 0x2f8430, Description: Retrieve User by ID
2018-11-26 22:07:32.458476+0100  localhost Docker[30178]: [Docker:] Terminator: Supervisor has failed, shutting down: Supervisor caught an error: one of the children died: com.docker.driver.amd64-linux (pid: 30255)
2018-11-26 22:07:32.458486+0100  localhost Docker[30178]: (libsystem_trace.dylib) Created Activity ID: 0x2f62b3, Description: Activity for state dumps
2018-11-26 22:07:32.458685+0100  localhost Docker[30178]:  statedump:
Current Network Paths
{
}
2018-11-26 22:07:32.490043+0100  localhost com.docker.supervisor[30196]: EOF on watchdog pipe: shutting down
2018-11-26 22:07:32.490187+0100  localhost com.docker.supervisor[30196]: Received terminated, shutting down
```

In the system log, there is just this entry:
```
Nov 26 22:07:32 xxx com.apple.xpc.launchd[1] (com.docker.docker.15196[30178]): Service exited with abnormal code: 1
```

Currently, I do not have more diagnostic logs. When this occurs again, I shall upload more logs and attach Diagnostic Ids to this ticket.

### Steps to reproduce the behavior

Issue is hard to reproduce. According to the diagnostic logs, it occurs at random after a GET or POST.

Thanks in advance for looking into this issue.
Please let me know if any more info would be useful for troubleshooting this.

**Comment by wyspaw** [comment]
Another diagnostic package regarding the issue uploaded.
Diagnostic ID: 4C17E1DE-1635-4835-8830-496E077CDAE9/20181128081356

**Comment by wyspaw** [comment]
Please see this package:
Diagnostic ID: 702B37EA-219F-44CF-A66B-3134049996A6/20181130093322

**Comment by hktalent** [comment]
#3458

**Comment by tsuna** [comment]
I believe I just got this on D4M 2.0.3.0 (31778)

```
2019-03-13 14:32:30.276582-0700  localhost com.docker.driver.amd64-linux[66104]: osxfs: start event: re-registering container 5d8ed2a371d81c22f52ddd1fd97b2b085a68a1cb4557220a206df7dc120d424c
2019-03-13 14:32:30.276774-0700  localhost com.docker.driver.amd64-linux[66104]: proxy >> GET /v1.24/containers/5d8ed2a371d81c22f52ddd1fd97b2b085a68a1cb4557220a206df7dc120d424c/json
2019-03-13 14:32:30.280819-0700  localhost com.docker.driver.amd64-linux[66104]: proxy << GET /v1.24/containers/5d8ed2a371d81c22f52ddd1fd97b2b085a68a1cb4557220a206df7dc120d424c/json (4.037367ms)
2019-03-13 14:32:30.283108-0700  localhost com.docker.supervisor[66101]: com.docker.driver.amd64-linux (pid: 66104): stderr: panic: runtime error: invalid memory address or nil pointer dereference
2019-03-13 14:32:30.283136-0700  localhost com.docker.supervisor[66101]: com.docker.driver.amd64-linux (pid: 66104): stderr: [signal SIGSEGV: segmentation violation code=0x1 addr=0x128 pc=0x4f65dc9]
2019-03-13 14:32:30.283171-0700  localhost com.docker.supervisor[66101]: com.docker.driver.amd64-linux (pid: 66104): stderr:
2019-03-13 14:32:30.283183-0700  localhost com.docker.supervisor[66101]: com.docker.driver.amd64-linux (pid: 66104): stderr: goroutine 40 [running]:
2019-03-13 14:32:30.284264-0700  localhost com.docker.supervisor[66101]: com.docker.driver.amd64-linux (pid: 66104): stderr: main.add(0x5581080, 0xc00003c800, 0x5595060, 0xc000072b50, 0xc0000e2100, 0xc00022e280, 0x40)
2019-03-13 14:32:30.284337-0700  localhost com.docker.supervisor[66101]: com.docker.driver.amd64-linux (pid: 66104): stderr:    /Users/administrator/jenkins/workspace/_desktop-build_edge-2.0.3.0-WF555IQHQ7DHKCAFHODEK7DS6BXRAJGCP5QDMEAZL26NF4DNNQGA/src/github.com/docker/pinata/mac/backend/cmd/com.docker.driver.amd64-linux/events.go:79 +0xb9
2019-03-13 14:32:30.284380-0700  localhost com.docker.supervisor[66101]: com.docker.driver.amd64-linux (pid: 66104): stderr: main.watch(0x5595060, 0xc000072b50, 0xc0000e2100, 0x0, 0x0)
2019-03-13 14:32:30.284393-0700  localhost com.docker.supervisor[66101]: com.docker.driver.amd64-linux (pid: 66104): stderr:    /Users/administrator/jenkins/workspace/_desktop-build_edge-2.0.3.0-WF555IQHQ7DHKCAFHODEK7DS6BXRAJGCP5QDMEAZL26NF4DNNQGA/src/github.com/docker/pinata/mac/backend/cmd/com.docker.driver.amd64-linux/events.go:54 +0x457
2019-03-13 14:32:30.284408-0700  localhost com.docker.supervisor[66101]: com.docker.driver.amd64-linux (pid: 66104): stderr: main.startWatchingEvents(0x5595060, 0xc000072b50, 0x1, 0xc000048717)
2019-03-13 14:32:30.284428-0700  localhost com.docker.supervisor[66101]: com.docker.driver.amd64-linux (pid: 66104): stderr:    /Users/administrator/jenkins/workspace/_desktop-build_edge-2.0.3.0-WF555IQHQ7DHKCAFHODEK7DS6BXRAJGCP5QDMEAZL26NF4DNNQGA/src/github.com/docker/pinata/mac/backend/cmd/com.docker.driver.amd64-linux/events.go:34 +0x1d0
2019-03-13 14:32:30.284441-0700  localhost com.docker.supervisor[66101]: com.docker.driver.amd64-linux (pid: 66104): stderr: main.run.func2(0xc000372120)
2019-03-13 14:32:30.284450-0700  localhost com.docker.supervisor[66101]: com.docker.driver.amd64-linux (pid: 66104): stderr:    /Users/administrator/jenkins/workspace/_desktop-build_edge-2.0.3.0-WF555IQHQ7DHKCAFHODEK7DS6BXRAJGCP5QDMEAZL26NF4DNNQGA/src/github.com/docker/pinata/mac/backend/cmd/com.docker.driver.amd64-linux/main.go:109 +0xb7
2019-03-13 14:32:30.284461-0700  localhost com.docker.supervisor[66101]: com.docker.driver.amd64-linux (pid: 66104): stderr: created by main.run
2019-03-13 14:32:30.284471-0700  localhost com.docker.supervisor[66101]: com.docker.driver.amd64-linux (pid: 66104): stderr:    /Users/administrator/jenkins/workspace/_desktop-build_edge-2.0.3.0-WF555IQHQ7DHKCAFHODEK7DS6BXRAJGCP5QDMEAZL26NF4DNNQGA/src/github.com/docker/pinata/mac/backend/cmd/com.docker.driver.amd64-linux/main.go:108 +0x383
2019-03-13 14:32:30.307684-0700  localhost com.docker.supervisor[66101]: cannot read stdout from com.docker.driver.amd64-linux (pid: 66104): EOF
2019-03-13 14:32:30.307743-0700  localhost com.docker.supervisor[66101]: cannot read stderr from com.docker.driver.amd64-linux (pid: 66104): EOF
2019-03-13 14:32:30.308222-0700  localhost com.docker.supervisor[66101]: Reap com.docker.driver.amd64-linux (pid: 66104): exit status 2
2019-03-13 14:32:30.309887-0700  localhost com.docker.supervisor[66101]: Stop 1 children with order 1: [com.docker.driver.amd64-linux (pid: 66104)]
2019-03-13 14:32:30.309935-0700  localhost com.docker.supervisor[66101]: Supervisor caught an error
2019-03-13 14:32:30.309946-0700  localhost com.docker.supervisor[66101]: StopAll
2019-03-13 14:32:30.309972-0700  localhost com.docker.supervisor[66101]: Stop 2 children with order 2: [com.docker.osxfs (pid: 66102) com.docker.vpnkit (pid: 66103)]
```

**Comment by guillaumerose** [comment]
I fixed the root cause of the panic of the last comment. The fix will be in the next edge version.

/reopen

**Comment by tsuna** [comment]
Any idea when this is going to hit the edge channel? My team keeps having D4M crashes with this signature... Thanks!

**Comment by guillaumerose** [comment]
You can try this build: https://download-stage.docker.com/mac/edge/Docker.dmg

The release should happen next week.

**Comment by tsuna** [comment]
Thanks, I'm trying it now. I'll report back if I see this crash again.

**Comment by tsuna** [comment]
Kubernetes doesn't work with this version.  I uploaded diagnostics (8CB32C31-B596-4FF0-8C20-F20F7594641B/20190409175910).

Not sure whether this is related:
```
2019-04-09T17:41:16Z docker I0409 17:41:16.945377    1344 kubelet.go:304] Watching apiserver
2019-04-09T17:41:16Z docker E0409 17:41:16.948501    1344 reflector.go:126] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Get https://192.168.65.3:6443/api/v1/pods?fieldSel
ector=spec.nodeName%3Ddocker-desktop&limit=500&resourceVersion=0: dial tcp 192.168.65.3:6443: connect: connection refused
2019-04-09T17:41:16Z docker E0409 17:41:16.949137    1344 reflector.go:126] k8s.io/kubernetes/pkg/kubelet/kubelet.go:442: Failed to list *v1.Service: Get https://192.168.65.3:6443/api/v1/services?limit=50
0&resourceVersion=0: dial tcp 192.168.65.3:6443: connect: connection refused
2019-04-09T17:41:16Z docker E0409 17:41:16.949804    1344 reflector.go:126] k8s.io/kubernetes/pkg/kubelet/kubelet.go:451: Failed to list *v1.Node: Get https://192.168.65.3:6443/api/v1/nodes?fieldSelector=
metadata.name%3Ddocker-desktop&limit=500&resourceVersion=0: dial tcp 192.168.65.3:6443: connect: connection refused
2019-04-09T17:41:16Z docker I0409 17:41:16.969691    1344 client.go:75] Connecting to docker on unix:///var/run/docker.sock
2019-04-09T17:41:16Z docker I0409 17:41:16.970324    1344 client.go:104] Start docker client with request timeout=2m0s
2019-04-09T17:41:16Z docker E0409 17:41:16.970889    1344 kube_docker_client.go:91] failed to retrieve docker version: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker dae
mon running?
2019-04-09T17:41:16Z docker W0409 17:41:16.970987    1344 kube_docker_client.go:92] Using empty version for docker client, this may sometimes cause compatibility issue.
2019-04-09T17:41:16Z docker F0409 17:41:16.972154    1344 server.go:265] failed to run Kubelet: failed to create kubelet: failed to get docker version: Cannot connect to the Docker daemon at unix:///var/r
un/docker.sock. Is the docker daemon running?
2019-04-09T17:41:16Z docker time="2019-04-09T17:41:16.984552068Z" level=warning msg="Running experimental build"
2019-04-09T17:41:16Z docker time="2019-04-09T17:41:16.985619553Z" level=warning msg="could not change group /var/run/docker.sock to docker: group docker not found"
2019-04-09T17:41:16Z docker time="2019-04-09T17:41:16.985933756Z" level=debug msg="Listener created for HTTP on unix (/var/run/docker.sock)"
```
I've waited about 20min and the UI still shows Kubernetes as "starting" and from macOS I'm getting EOF when trying to do anything.

**Comment by guillaumerose** [comment]
Try a reset factory default. Maybe some old Kubernetes stuff (etcd, or others) are still present.

**Comment by tsuna** [comment]
Confirmed, resetting to factory defaults "fixed" it.
