### ISSUE TITLE
"Fatal error Docker is already running" after 2.3.0.2 upgrade

### ISSUE THREAD

**Issue by pinko-fowle** [docker/for-mac#4832]
- [X ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

Docker starts at startup

### Actual behavior

"Fatal error Docker is already running" and no docker starts.

### Information

  - macOS Version: macOS Catalina 10.15.4

This is a duplicate of #4556 but you closed the issue before fixing or doing anything about it.

This is a super annoying issue for everyone on my team. We only just found how to fix it.

Please make the next installer fix this situation.

Also the fact that when this happens no Docker is left running is really frustrating.

Also please get rid of your very very annoying & frustrating Lockbot. This is an enormous roadblock to forward progress.

**Comment by stephen-turner** [comment]
The lockbot locks tickets that have already been closed. If the tickets are closed, no-one will see the comments anyway, so it would be pointless to allow people to write on them. In this case, the original reporter closed the issue having said that it was resolved.

**Comment by stephen-turner** [comment]
If you are still experiencing it, please describe the steps to reproduce. It's not common or we would have had hundreds of reports of it.

**Comment by pinko-fowle** [comment]
I am still experiencing this issue until I went & resolved it myself, using the same manual steps the author faced in #4556 

I can continue to tell my team to all go follow these steps, but I fully believe this to be a regular issue faced.

> If the tickets are closed, no-one will see the comments anyway, 

What makes you say that? Do you mean @docker won't see the comments? Because certainly anyone who happens upon an issue that pertains to them, even closed issues, would benefit from further contributions in that ticket. I'm not sure what you mean by no-one will see the comments. That is not my experience.

**Comment by yamagame** [comment]
I tried launch "Docker Desktop.app" with command line.

This command is "Fatal error Docker is already running".
`$ "/Applications/Docker.app/Contents/MacOS/Docker Desktop.app/Contents/MacOS/Docker Desktop"`

But this command is no problem.
`$ "/Applications/Docker.app/Contents/MacOS/Docker Desktop.app/Contents/MacOS/Docker Desktop" --name=containers`

--name=containers option is important.
"Docker Desktop.app" on osx finder's dock dose not have this option.
