### ISSUE TITLE
M1 Preview won't start when NetworkSharing Network != 192.168.64.1

### ISSUE THREAD

**Issue by SteffenDE** [docker/for-mac#5149]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

Running the M1 preview boots on a Mac that was restored from a Time Machine backup.

### Actual behavior

M1 preview hangs indefinitely and does not start.

### Information

  - macOS Version: 11.1

I think this is related to VMWare Fusion as I've had Virtual Machines on my Intel MacBook in the `bridge100` interface network `192.168.226.0/24`. After restoring the M1 MacBook from TimeMachine, the `bridge100` interface (now seemingly in use by docker) still had the same `192.168.226.0/24` network configured.

Running
```bash
sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.nat NAT -dict-add SharingNetworkMask 255.255.255.0
sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.nat NAT -dict-add SharingNetworkNumberEnd 192.168.64.255
sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.nat NAT -dict-add SharingNetworkNumberStart 192.168.64.1
```
fixed this problem for me and docker now starts fine.

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. Restore M1 Mac from a Backup that had VMWare Fusion installed or change SharingNetworkNumber
  2. Docker tries to start with `192.168.64.0/24` network and won't finish starting

I think this is a bug as Docker on Intel was running fine next to VMWare Fusion's `192.168.226.0/24` network.

**Comment by stephen-turner** [comment]
Thanks for the report. I think we've still got some IP addresses hard-coded in this preview build.

**Comment by sfuerte** [comment]
duplicate of https://github.com/docker/for-mac/issues/5130 ?

**Comment by SteffenDE** [comment]
I think the symptoms may be the same, but I'm not sure if the underlying reason is the same too. I'm not seeing any error due to timeouts in the log, just some `still waiting for docker to respond after xy` here and then.
I'm also pretty sure that this issue here is specifically related to having VMWare Fusion or another software running besides docker that uses the `bridge100` interface.

But if it's the same feel free to close this issue.

**Comment by guglen** [comment]
Does someone have a solution?

**Comment by SteffenDE** [comment]
> Does someone have a solution?

As stated in my initial comment:

> Running
> ```
> sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.nat NAT -dict-add SharingNetworkMask > 255.255.255.0
> sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.nat NAT -dict-add SharingNetworkNumberEnd > 192.168.64.255
> sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.nat NAT -dict-add SharingNetworkNumberStart > 192.168.64.1
> ```
> fixed this problem for me and docker now starts fine.

**Comment by guglen** [comment]
> > Does someone have a solution?
> 
> As stated in my initial comment:
> 
> > Running
> > ```
> > sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.nat NAT -dict-add SharingNetworkMask > 255.255.255.0
> > sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.nat NAT -dict-add SharingNetworkNumberEnd > 192.168.64.255
> > sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.nat NAT -dict-add SharingNetworkNumberStart > 192.168.64.1
> > ```
> > 
> > 
> > fixed this problem for me and docker now starts fine.



can you please tell me the steps you have performed?

**Comment by SteffenDE** [comment]
You've **already quoted** the commands that you must run execute using the macOS **terminal**. If you aren't sure how to do this, maybe you should wait for a release where this is not necessary any more.

**Comment by guglen** [comment]
thnks Steffen,

the problem of IP 192.168.65.1 of the bridge card "seems" to have been solved by modifying the file

/Library/preferences/SystemConfiguration/com.apple.vmnet.plist

by editing the final part of the file:

         <key> Shared_Net_Address </key>
         <string> 192.168.64.1 </string>
         <key> Shared_Net_Mask </key>
         <string> 255.255.255.0 </string>

**Comment by rededge-ian** [comment]
I am also experiencing this issue on an M1 Mac, although I believe in my case it may have be caused by an existing Parallels Desktop Preview installation. This computer was not restored by Time Machine, but a lot of the ~/Library directory was copied over from an existing Intel Mac.

Unfortunately neither @SteffenDE's defaults edits, nor the SystemConfiguration/com.apple.vmnet.plist Shared_Net_Address edit, seem to work. Uninstalling Parallels also did not fix the issue.

Docker will show the error `INFO[0220] cannot set up multiplexer, will retry in 2s: dial tcp 192.168.64.1:1999: connect: network is unreachable` until I run `sudo ifconfig bridge100 inet 192.168.64.1 netmask 255.255.255.0`.

At that point Docker will finish starting, but calls to the Docker registry to pull down images will fail since it seems to be calling 192.168.173.1 instead of 64.1:

```
% docker run -d -p 80:80 docker/getting-started
Unable to find image 'docker/getting-started:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.173.1:53: read udp 192.168.173.5:33708->192.168.173.1:53: i/o timeout.
```


If I restart Docker, the SystemConfiguration/com.apple.vmnet.plist Shared_Net_Address is reset to `192.168.173.1` and bridge100 shows 
```
inet 192.168.173.1 netmask 0xffffff00 broadcast 192.168.173.255
inet6 fe80::c8a:1c87:b429:c106%bridge100 prefixlen 64 secured scopeid 0x14
```

**Comment by rededge-ian** [comment]
The latest version of the M1 preview has resolved this issue.

**Comment by clairegraham** [comment]
Still broken in latest preview release I just tried, from ```https://desktop.docker.com/mac/stable/arm64/60984/Docker.dmg```

Same error in console.log that never stops, and Docker never successfully starts up (unless the Mac firewall is disabled):

```
INFO[0026] connecting to tcp+bootstrap+client://gateway.docker.internal:62734/3a430e9d1d3953fcb729cd42cf32d7bdf6fde436e23ff44e1ed3f13fac358511...
INFO[0026] cannot set up multiplexer, will retry in 2s: querying route for 8.8.8.8: network is unreachable
INFO[0028] connecting to tcp+bootstrap+client://gateway.docker.internal:62734/3a430e9d1d3953fcb729cd42cf32d7bdf6fde436e23ff44e1ed3f13fac358511...
INFO[0028] cannot set up multiplexer, will retry in 2s: querying route for 8.8.8.8: network is unreachable
```

**Comment by stephen-turner** [comment]
I'm pretty sure this was fixed a long time ago, closing.
