### ISSUE TITLE
cannot use devdns container with 3.2.0; port 53 is in use

### ISSUE THREAD

**Issue by mattmoskwa** [docker/for-mac#5416]
- [ x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Should be able to use devdvs container
### Actual behavior
Devdns container errors on start with message:
```
docker: Error response from daemon: driver failed programming external connectivity on endpoint devdns (3b7e6e3c584ed6e9a0f690fd36dbe6dfccd2ad6f4dd4bb401e0a56bc6e60edea): Error starting userland proxy: listen udp4 0.0.0.0:53: bind: address already in use.
```
### Information

  - macOS Version: 10.15.7
  - Docker Desktop Version: 3.2.0

### Steps to reproduce the behavior

  1. 
```
  docker run -d --name devdns -p 53:53/udp \
      -v /var/run/docker.sock:/var/run/docker.sock:ro ruudud/devdns
```
  Nothing is running on port 53, which I confirmed with `sudo lsof -i :53`

**Comment by pusewicz** [comment]
Exactly the same problem on two other machines after upgrading.

**Comment by gkl1368** [comment]
I have the same problem, the docker version is 3.2.0 and 3.2.1

**Comment by shamelesscookie** [comment]
Just want to +1 as I'm also having this issue in Docker 3.2.1 on Windows 10 x64 19042.804.

On the Windows side, the Microsoft `SharedAccess` service is bound to 0.0.0.0:53 UDP, but that doesn't stop Docker 3.1.0 from also binding to this port:

![image](https://user-images.githubusercontent.com/36210509/110241241-bf962780-7f1d-11eb-8319-2a59ada6dad3.png)

**Comment by danquah** [comment]
Same issue here on docker for mac (3.2.1). 
Reproduce like this:
```
$ docker run --rm -p 53:53/udp jpillora/dnsmasq
docker: Error response from daemon: driver failed programming external connectivity on endpoint pedantic_roentgen (00d18f994192e19f5c634bb32aaaeb0880e5eb90a14aba30269b069343698b8e): Error starting userland proxy: listen udp4 0.0.0.0:53: bind: address already in use.
```

Dug a bit deeper by entering into the vm that runs the docker deamon and took a look around:
```
$ docker run -it --privileged --pid=host justincormack/nsenter1
/ # netstat -tunalp
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      1260/rpcbind
tcp        0      0 192.168.65.4:53         0.0.0.0:*               LISTEN      1069/dns-forwarder
tcp        0      0 0.0.0.0:59773           0.0.0.0:*               LISTEN      1311/rpc.statd
tcp        0      0 :::111                  :::*                    LISTEN      1260/rpcbind
tcp        0      0 :::57601                :::*                    LISTEN      1311/rpc.statd
udp        0      0 127.0.0.1:639           0.0.0.0:*                           1311/rpc.statd
udp        0      0 0.0.0.0:62771           0.0.0.0:*                           1311/rpc.statd
udp        0      0 192.168.65.4:53         0.0.0.0:*                           1069/dns-forwarder
udp        0      0 0.0.0.0:68              0.0.0.0:*                           955/dhcpcd: [master
udp        0      0 0.0.0.0:111             0.0.0.0:*                           1260/rpcbind
udp        0      0 127.0.0.1:123           0.0.0.0:*                           1280/start
udp        0      0 :::55386                :::*                                1311/rpc.statd
udp        0      0 :::111                  :::*                                1260/rpcbind
```

It seems we have "dns-forwarder" process running (it's not present in version 3.2.0), and it is taking port 53. If I kill the process (which probably breaks all sorts of things) my sample container starts just fine.

```
/ # kill 1069
/ # exit
(back in my main shell)
$ docker run --rm -p 53:53/udp jpillora/dnsmasq
[webproc] 2021/03/09 11:17:39 loaded config files changes from disk
[webproc] 2021/03/09 11:17:39 agent listening on http://0.0.0.0:8080...
dnsmasq: started, version 2.80 cachesize 150
dnsmasq: compile time options: IPv6 GNU-getopt no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset auth no-DNSSEC loop-detect inotify dumpfile
dnsmasq: using nameserver 10.0.0.1#53 for domain company
dnsmasq: using nameserver 1.1.1.1#53
dnsmasq: using nameserver 1.0.0.1#53
dnsmasq: read /etc/hosts - 7 addresses
```

**Comment by danquah** [comment]
So to summarise a bit:

* It seems that the linux VM that is used behind the scenes host the docker deamon now itself runs an internal container (dns-forwarder) that runs on port 53 and thus blocks "user"-containers from taking that port
* dns-forwarder is as far as I can tell an internal docker project (took a look inside the go-binary and it references an internal docker repository), so I could't really tell any more about it, but from its name my guess it is supposed to pass dns-requests from containers back to the host OSs resolver, ie. the nameserver in /etc/resolve.conf in running containers is referencing this server or something that depends on it. This is somewhat confirmed by the fact that dns stops working inside running containers when I kill the dns-forwarder.
* This issue seems unrelated to another open DNS issue: #5335 (which as far as I can tell is caused by an actual dns deamon running on the host macos)
* It seems that you can downgrade without any problems, so if you run in to this, just revert back to version 3.2.0 again [mac](https://desktop.docker.com/mac/stable/amd64/61504/Docker.dmg) [windows](https://desktop.docker.com/win/stable/amd64/61504/Docker%20Desktop%20Installer.exe)

**Comment by Gunhedo** [comment]
> * It seems that you can downgrade without any problems, so if you run in to this, just revert back to version 3.2.0 again ( Mac [releases](https://docs.docker.com/docker-for-mac/release-notes/), Windows  [releases](https://docs.docker.com/docker-for-windows/release-notes/) )

It (Docker) was automatically updating to the latest version after a restart of docker, when I did so on Docker for Windows. There's no option to prevent that and this is intentionally as far as i could gather.

**Comment by blymemikkel** [comment]
> It (Docker) was automatically updating to the latest version after a restart of docker, when I did so on Docker for Windows. There's no option to prevent that and this is intentionally as far as i could gather.
I think they're working on that https://github.com/docker/roadmap/issues/183

**Comment by mattmoskwa** [comment]
I was able to get the container running with workaround suggested in https://github.com/docker/for-mac/issues/5416#issuecomment-792278189 on Mac

```
docker run -d --name devdns -p 192.168.1.3:53:53/udp -v /var/run/docker.sock:/var/run/docker.sock:ro ruudud/devdns
```

**Comment by drytoastman** [comment]
Same issue after 3.2.0.

You can still bind to any local windows interface addresses specifically, even the WSL address and it works  i.e. -p 127.0.0.1:53:53, -p 192.168.X.Y:53:53, -p 172.X.Y.Z:53:53

However, if you bind to 0.0.0.0:53 (which is default without an IP), that is when it gets blocked by the internal dns-forwarder.

**Comment by StefanScherer** [comment]
@mattmoskwa @pusewicz @gkl1368 @labbydev @danquah @drytoastman @Gunhedo While we're preparing a patch release 3.2.2 next week I can share a bugfix installer [Docker Desktop for Mac, build 61849](https://desktop-stage.docker.com/mac/stable/amd64/61849/Docker.dmg)
It would be great to get early feedback if everything works fine for your use-cases.

**Comment by danquah** [comment]
Triede it out, and it works! (with a caviat)

```
# Using version 3.2.1
# Any container that binds to port 53 will do here
$ docker run --rm -p 53:53 jpillora/dnsmasq
docker: Error response from daemon: Ports are not available: listen tcp 0.0.0.0:53: bind: address already in use.
ERRO[0000] error waiting for container: context canceled

# Then using build 61849
$ docker run --rm -p 53:53 jpillora/dnsmasq
[webproc] 2021/03/13 14:11:16 loaded config files changes from disk
[webproc] 2021/03/13 14:11:16 agent listening on http://0.0.0.0:8080...
dnsmasq: started, version 2.80 cachesize 150
(more output)
```

Now for the caviat: If I enable the new "Use new virtualization framework" flag, MacOS starts a "mDNSResponder" process on the host, which again takes up port 53. This is one of the topics over at #5335 , and seems unrelated to the issue being addressed by the build.

So all in all, a big 👍 :)

**Comment by mattmoskwa** [comment]
> @mattmoskwa @pusewicz @gkl1368 @labbydev @danquah @drytoastman @Gunhedo While we're preparing a patch release 3.2.2 next week I can share a bugfix installer [Docker Desktop for Mac, build 61849](https://desktop-stage.docker.com/mac/stable/amd64/61849/Docker.dmg)
> It would be great to get early feedback if everything works fine for your use-cases.

Can confirm this works for my environment as well. Thanks so much!

**Comment by nicekiwi** [comment]
> 
> 
> @mattmoskwa @pusewicz @gkl1368 @labbydev @danquah @drytoastman @Gunhedo While we're preparing a patch release 3.2.2 next week I can share a bugfix installer [Docker Desktop for Mac, build 61849](https://desktop-stage.docker.com/mac/stable/amd64/61849/Docker.dmg)
> It would be great to get early feedback if everything works fine for your use-cases.

Is there a windows installer I can try too?

**Comment by nicekiwi** [comment]
> @mattmoskwa @pusewicz @gkl1368 @labbydev @danquah @drytoastman @Gunhedo While we're preparing a patch release 3.2.2 next week I can share a bugfix installer [Docker Desktop for Mac, build 61849](https://desktop-stage.docker.com/mac/stable/amd64/61849/Docker.dmg)
> It would be great to get early feedback if everything works fine for your use-cases.

Unfortunately this does not resolve the port 53 binding issues for me. Running DNSmasq in a container.

**Comment by eexit** [comment]
> @mattmoskwa @pusewicz @gkl1368 @labbydev @danquah @drytoastman @Gunhedo While we're preparing a patch release 3.2.2 next week I can share a bugfix installer [Docker Desktop for Mac, build 61849](https://desktop-stage.docker.com/mac/stable/amd64/61849/Docker.dmg)
> It would be great to get early feedback if everything works fine for your use-cases.

Works like a charm! We don't use K8s so it means "new virtualization framework" is off.
Many thanks!

**Comment by stephen-turner** [comment]
Thanks for the feedback, everyone. This issue is fixed in version 3.2.2, which we have just released.
