### ISSUE TITLE
Regression: Container with many published ports takes 10x slower to start in Docker Desktop for Mac 3.3.x

### ISSUE THREAD

**Issue by stanleymho** [docker/for-mac#5668]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

Running the following command to start a container with 100 published ports used to take only 3-4 seconds in Docker Desktop for Mac 3.0.3:
```
$ time docker run -p 30000-30100:30000-30100 -it busybox sh -c "exit"
real	0m3.434s
user	0m0.160s
sys	0m0.141s
```

### Actual behavior

Running the same command with Docker Desktop for Mac 3.3.x now takes order of magnitude longer:
```
$ time docker run -p 30000-30100:30000-30100 -it busybox sh -c "exit"
real	3m43.009s
user	0m0.174s
sys	0m0.131s
```

### Information

* This used to work fine with Docker Desktop 3.0.3.
* This problem is new after I upgrade to Docker Desktop 3.3.1 and 3.3.3. It is very reproducible.

  - macOS Version: 11.3.0 and 11.3.1.
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 3.3.1 and 3.3.3

Looking at the dockerd logs, it seems like the Docker daemon is busy doing lots of iptables invocations:
```
2021-05-07T23:01:54Z dockerd time="2021-05-07T23:01:54.054250300Z" level=debug msg="/usr/sbin/iptables, [--wait -t filter -C DOCKER ! -i docker0 -o docker0 -p tcp -d 172.17.0.2 --dport 30023 -j ACCEPT]"
2021-05-07T23:01:54Z dockerd time="2021-05-07T23:01:54.146419100Z" level=debug msg="/usr/sbin/iptables, [--wait -t filter -D DOCKER ! -i docker0 -o docker0 -p tcp -d 172.17.0.2 --dport 30023 -j ACCEPT]"
```

### Steps to reproduce the behavior

1. Simply run the following command:
```
time docker run -p 30000-30100:30000-30100 -it busybox sh -c "exit"
```

**Comment by MaSpeng** [comment]
I can confirm this issue, for me and my colleague this issue started with Docker Desktop 3.3.0 and continued to the latest version (by now 3.3.3).

**Comment by CraigLangford** [comment]
Confirmed as well, reverting to 3.2 fixes the issue.

**Comment by djs55** [comment]
Thanks for the reports. I think you're right about `iptables` being the problem -- I replaced `iptables` with a shell script that calls `exit 0` and the `docker run` took 3 seconds. I'll add a ticket to our backlog.

**Comment by stephen-turner** [comment]
May be due to switching to a later kernel.

**Comment by joaopbnogueira** [comment]
Just wanted to second this issue, as it's driving me nuts. 3.2 works fine but keeps automatically updating to 3.3, which doesn't work fine and takes over 150 seconds to do an "up" vs a few seconds on 3.2. I also have a roughly 100 port maps

```
ports:
      - "5432:5432" # postgres
      - "6379:6379" # redis
      - "80:80" # nginx
      - "443:443" # nginx
      - "5060-5061:5060-5061/udp" # sip
      - "10000-10100:10000-10100/udp" #rtp
      - "389:389" # ldap
      - "5038:5038" # asterisk
```

DiagnosticsID: AF628F15-7B04-4806-BEE7-33B5827B55A8/20210513171144

**Comment by stephen-turner** [comment]
This looks the same as this upstream issue: moby/moby#39590. But that wouldn't explain why it was a recent regression in Desktop.

**Comment by jforge** [comment]
Also want to second this issue, reason mentioned by @joaopbnogueira.
I narrowed a problem down to docker-for-mac only (no issues with linux and windows), then I saw this issue here.

Currently docker-for-mac 3.3.3 is unusable for me, when it comes to port range mapping, some measurements with 3.3.3:

`
time docker run --rm alpine echo test
-> 0.784 total
time docker run --rm -p 10000:10000 alpine echo test
-> 3.167 total
time docker run --rm -p 10000-10005:10000-10005/tcp alpine echo test
-> 15.099 total
time docker run --rm -p 10000-10010:10000-10010/tcp alpine echo test
-> 26.815 total
time docker run --rm -p 10000-10050:10000-10050/tcp alpine echo test 
-> 2:03.73 total
docker run --rm -p 10000-10100:10000-10100/tcp alpine echo test
-> 4:02.61 total
`

**Comment by randomvariable** [comment]
The change from iptables to nftables would have been at the distro level (Alpine?) rather than the kernel, e.g. this doesn't seem to be an issue on full Linux hosts with up to date kernels.

**Comment by sbrawner** [comment]
Wanted to know if this was being worked at all, considering the issue @stephen-turner mentioned is two years old and doesn't appear to have any priority.  Also if anyone has workarounds for 3.x, would be good to know

**Comment by stephen-turner** [comment]
We're trying to see if there are any quick fixes we can do within Docker Desktop. That would be much quicker than fixing the issue "properly" upstream, which depends on some very large changes to libnetwork. It's 50/50 at the moment though.

**Comment by fredericdalleau** [comment]
The build below should fix the issue:
amd64: https://desktop-stage.docker.com/mac/stable/amd64/66048/Docker.dmg
arm64: https://desktop-stage.docker.com/mac/stable/arm64/66048/Docker.dmg
Please feedback !

**Comment by jforge** [comment]
Thanks for this version (Docker Desktop 3.6.0 (3.6.0.5313)).
I see drastic improvements in startup times.
My test suite shows values, that are totally acceptable for me.

time docker run --rm alpine echo test
-> 0.624 total
time docker run --rm -p 10000:10000 alpine echo test
-> 0.839 total
time docker run --rm -p 10000-10005:10000-10005/tcp alpine echo test
-> 1.556 total
time docker run --rm -p 10000-10010:10000-10010/tcp alpine echo test
-> 2.412 total
time docker run --rm -p 10000-10050:10000-10050/tcp alpine echo test 
-> 8.955 total
time docker run --rm -p 10000-10100:10000-10100/tcp alpine echo test
-> 17.573 total

**Comment by stanleymho** [comment]
Thanks for the fix. My actual use case requires 400 ports, and here are the numbers I have comparing Docker Desktop 3.2.2 with this fix:

Docker Desktop 3.2.2
----------------------
$ time docker run --rm -p 10000-10100:10000-10100/tcp alpine echo test
-> 0m7.941s

$ time docker run --rm -p 40000-40399:40000-40399/tcp alpine echo test
-> 0m30.393s

This fix
-------
$ time docker run --rm -p 10000-10100:10000-10100/tcp alpine echo test
-> 0m22.697s

$ time docker run --rm -p 40000-40399:40000-40399/tcp alpine echo test
-> 1m29.665s

This fix does address my original performance problem with 400 ports significantly, by cutting down the time from > 10 mins to 1.5 mins. That said, this is still 3x slower compared to Docker Desktop 3.2.2.

Is there anything in addition could be done to bring the performance back to the 3.2.2 level?

**Comment by stephen-turner** [comment]
Thanks for the benchmarking, @stanleymho, that's very informative.

I'm not sure how much more we will be able to do without moby/moby#39590 being fixed upstream, or downgrading the kernel again (which we're not going to do because it would leave us stuck on an old kernel indefinitely).

**Comment by stanleymho** [comment]
That's unfortunate. If this is the case, I will take this fix which is still good step forwards. What's the timeframe for the release?

**Comment by stephen-turner** [comment]
It just missed 3.5.0/3.5.1, so it will be in 3.6.0. We release approximately monthly, although the dates aren't completely fixed. If we do a 3.5.2 for some other reason we'll try and slip this fix in too. You're welcome to continue to use the staging builds in the mean time, of course.

**Comment by stanleymho** [comment]
@stephen-turner Looks like the Docker Desktop with this fix still invokes iptables for each port under the cover. My understanding is that the iptables command has a multiport extension which allows multiple ports to be specified (it's up to 15 ports max). I wonder if Docker Desktop could take advantage of this, and cut down the number of iptables invocations to speed up the performance.

**Comment by fredericdalleau** [comment]
Here is another build that will bring the numbers back to 3.2.2
https://desktop-stage.docker.com/mac/stable/amd64/66183/Docker.dmg
https://desktop-stage.docker.com/mac/stable/arm64/66183/Docker.dmg
Let me know how it goes,

**Comment by stanleymho** [comment]
@fredericdalleau Thanks for the fix. The performance looks great, and the numbers are even better than 3.2.2:
```
$ time docker run --rm -p 10000-10100:10000-10100/tcp alpine echo test
-> 0m7.941s (Docker 3.2.2)
-> 0m22.697s (Previous fix)
-> 0m5.053s (Latest fix)

$ time docker run --rm -p 40000-40499:40000-40499/tcp alpine echo test
-> 0m30.393s (Docker 3.2.2)
-> 1m29.665s (Previous fix)
-> 0m25.396s (Latest fix)
```
That said, is this build supposed to be fully functional? I tried running kind (https://github.com/kubernetes-sigs/kind) with this build, and I ran into some issues which didn't occur before:
```
$ kind create cluster --name xyz --wait 90s
 ✓ Ensuring node image (kindest/node:v1.20.2) 🖼 
 ✓ Preparing nodes 📦  
 ✓ Writing configuration 📜 
 ✓ Starting control-plane 🕹️ 
 ✓ Installing CNI 🔌 
 ✓ Installing StorageClass 💾 
 ✗ Waiting ≤ 1m30s for control-plane = Ready ⏳ 
 • WARNING: Timed out waiting for Ready ⚠️
```
and Kind was failing with this latest Docker build due to some networking issue.

**Comment by fredericdalleau** [comment]
@stanleymho, we have some kubernetes test in the CI and they passed.

**Comment by dreis2211** [comment]
@fredericdalleau Care to share the commits or PRs with the improvements for interested people like me?

**Comment by fredericdalleau** [comment]
@dreis2211 it's a configuration change on the linuxkit kernel. I'll share a PR, and will link here.

**Comment by fredericdalleau** [comment]
@stanleymho I gave it a quick try and `kind` created the cluster (kubernetes 1.21.1). You may want to remove the `--wait` just in case.

**Comment by stanleymho** [comment]
@fredericdalleau After I restarted Docker Desktop, `kind` now works properly with the latest your build on my machine.

**Comment by stanleymho** [comment]
Is there any update on when this fix will be officially shipped with Docker Desktop?

**Comment by stephen-turner** [comment]
Ah, sorry, I believe we already fixed this in 3.5.2 but forgot to update this ticket. Please test and let me know.

**Comment by stanleymho** [comment]
I have tried out 3.5.2. The fix did improve the performance quite a bit, but it seems like it was based on the initial fix: https://github.com/docker/for-mac/issues/5668#issuecomment-870386870:
```
$ time docker run --rm -p 10000-10100:10000-10100/tcp alpine echo test
real	0m23.019s
user	0m0.156s
sys	0m0.092s

$ time docker run --rm -p 40000-40499:40000-40499/tcp alpine echo test
real	1m53.724s
user	0m0.159s
sys	0m0.100s
```

These performance numbers were still not back to the 3.2.2 level. I think there is one additional fix we need, but it didn't seem like it was incorporated into 3.5.2: https://github.com/linuxkit/linuxkit/pull/3701

**Comment by stephen-turner** [comment]
That's correct.

**Comment by stanleymho** [comment]
Is there any update on when the additional fix (https://github.com/docker/for-mac/issues/5668) will be incorporated into the Docker Desktop?

**Comment by stephen-turner** [comment]
Still this:

> It just missed 3.5.0/3.5.1, so it will be in 3.6.0. We release approximately monthly, although the dates aren't completely fixed. If we do a 3.5.2 for some other reason we'll try and slip this fix in too. You're welcome to continue to use the staging builds in the mean time, of course.

**Comment by stanleymho** [comment]
I just tried out the new Docker Desktop 3.6.0 release, and the performance issue is fixed:
```
$ time docker run --rm -p 10000-10100:10000-10100/tcp alpine echo test
real	0m5.181s
user	0m0.152s
sys	0m0.097s

$ time docker run --rm -p 10000-10500:10000-10500/tcp alpine echo test
real	0m25.443s
user	0m0.162s
sys	0m0.103s
```

Thanks everyone!

**Comment by thaJeztah** [comment]
Thanks for confirming it's fixed! For those interested, the issue on was fixed through https://github.com/linuxkit/linuxkit/pull/3701 (mentioned above), which was an "interesting" find by @fredericdalleau. I'll quote his description from that pull request here (the lwn.net article is a fun read as well);

> #### Disable CONFIG_BPFILTER and CONFIG_BPFILTER_UMH
> 
> CONFIG_BPFILTER is aimed to provide a replacement for netfilter.
> 
> When CONFIG_BPFILTER is enabled, the kernel tries to contact a user mode helper
> for each iptable rule update. However the implementation of this helper has not
> been upstreamed yet. The communication thus fails and the kernel then falls back
> to netfilter.
> As a result, the rule update takes more than ten times the duration of the
> netfilter implementation alone.
> 
> This has been reported by Docker Desktop users for whom it can take minutes to
> start a container sharing a few hundred ports. [docker/for-mac#5668](https://github.com/docker/for-mac/issues/5668)
> 
> More details on the situation is described in https://lwn.net/Articles/822744/.


I opened a pull request to also add this to the release notes https://github.com/docker/docker.github.io/pull/13351


Let me go ahead and close this ticket! 🎉 🥳
