### ISSUE TITLE
Can't skip update even if pro

### ISSUE THREAD

**Issue by john8329** [docker/for-mac#5842]
- [] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
If I click "Skip this update [Pro]" it should skip the update and remove the dialog.

### Actual behavior
It doesn't do it, even considering that my account is pro. It's a fake button.

Even the presence of a button that requires paying to avoid an update is a grotesque windows-style pattern that just produces frustration in the user because of the feeling of lack of control.

### Information

  - macOS Version: 10.14.6
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 3.3.3 64133

<img width="552" alt="Screenshot 2021-07-14 at 17 29 37" src="https://user-images.githubusercontent.com/42315498/125649295-4ed14832-5ab0-42af-afc8-0de874c9e52e.png">

**Comment by stephen-turner** [comment]
Thanks for the feedback. I'm not sure why the button didn't work for you, but in any case we've already removed it (or rather, made it available to everyone not just Pro) in the latest version.

**Comment by StefanScherer** [comment]
I'm going to reopen this ticket to track progress. Thanks for reporting this. We found the root cause and we'll ship the fix with the next release. We'll keep you updated and close this ticket once the fix is available.

**Comment by RobinHoutevelts** [comment]
> Thanks for the feedback. I'm not sure why the button didn't work for you, but in any case we've already removed it (**or rather, made it available to everyone not just Pro**) in the latest version.

Is the annoying daily popup gone then for free users?

**Comment by stephen-turner** [comment]
If you hit Snooze it comes back tomorrow, but everyone can Skip This Update.

**Comment by RobinHoutevelts** [comment]
Thanks for clearing that up.

Still don't understand why being able to disable automatic update checks became paid.

Besides just really getting me angry, was there any other reason for introducing it? I can't seem to find any rationale.

**Comment by stephen-turner** [comment]
The history was that we want everyone to be on the latest version, so at first we updated everyone automatically. Later we made an exception for businesses because they told us that they have additional constraints that mean they can't update as quickly as personal users.

Having said all that, we have acknowledged that it was a mistake. But that's how it happened.

**Comment by ulyssessouza** [comment]
Hello. Docker Desktop 3.6.0 has been released containing a fix for this issue.
So I'm closing the ticket. Please feel free to reopen if the problem persists.

**Comment by aleksandrs-ledovskis** [comment]
> The history was that we want everyone to be on the latest version, so at first we updated everyone automatically. Later we made an exception for businesses because they told us that they have additional constraints that mean they can't update as quickly as personal users.

Clearly, in hindsight, the Docker Desktop v4.0.0 licensing changes were obviously in the making and this was the **real reason** - to force users to v4.0.0 and hope that they stay & pay.
