### ISSUE TITLE
Feature Request: Improve proxy configuration for all components

### ISSUE THREAD

**Issue by bb-Ricardo** [docker/for-mac#6319]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics

### Expected behavior
* To be able to configure proxies for different components

### Actual behavior
* only one proxy setting for all components is available (and broken in 4.8.1)
* no_proxy setting is ignored

  - macOS Version: 11.6.5
  - Intel chip or Apple chip: Inel
  - Docker Desktop Version: 4.7.1 (downgraded due to working proxy settings)

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`
```
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0017: can a VM be started?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[WARN] DD0033: does the host have Internet access? unable to fetch http://docker.com/
segment 2022/05/17 10:03:49 ERROR: sending request - Post "https://api.segment.io/v1/batch": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
segment 2022/05/17 10:03:49 ERROR: 1 messages dropped because they failed to be sent and the client was closed

Please note the following 1 warning:

1 : The check: does the host have Internet access?
    Produced the following warning: unable to fetch http://docker.com/

If the host does not have Internet access then containers will also not have Internet access.

The lack of Internet access could be caused by
- physical disconnection: check your ethernet cable or Wifi network
- the local network firewall policy: check with your IT department if access to docker.com is expected to work
- a VPN (or lack of one): try again with or without the VPN running

No fatal errors detected.
```
`cat ~/Library/Group\ Containers/group.com.docker/settings.json`
```
{
  "acceptCanaryUpdates": false,
  "activeOrganizationName": "",
  "analyticsEnabled": false,
  "autoDownloadUpdates": false,
  "autoStart": false,
  "backupData": false,
  "cpus": 8,
  "credentialHelper": "docker-credential-osxkeychain",
  "dataFolder": "/Users/XXX/Library/Containers/com.docker.docker/Data/vms/0/data",
  "deprecatedCgroupv1": false,
  "disableHardwareAcceleration": false,
  "disableTips": true,
  "disableUpdate": false,
  "diskFlush": "os",
  "diskQcowCompactAfter": 262144,
  "diskQcowKeepErased": 262144,
  "diskQcowRuntimeAsserts": false,
  "diskSizeMiB": 61035,
  "diskStats": "",
  "diskTRIM": true,
  "displayRestartDialog": true,
  "displaySwitchVersionPack": true,
  "displayedDeprecate1014": false,
  "displayedElectronPopup": [],
  "displayedExtensionsIntroductionDialog": false,
  "displayedTutorial": false,
  "dockerAppLaunchPath": "/Applications/Docker.app",
  "extensionsEnabled": true,
  "filesharingDirectories": [
    "/tmp",
    "/Users",
    "/Volumes",
    "/private",
    "/var/folders"
  ],
  "firstLaunchTime": 1649484017,
  "kubernetesEnabled": false,
  "kubernetesInitialInstallPerformed": false,
  "lastLoginDate": 0,
  "latestBannerKey": "",
  "licenseTermsVersion": 2,
  "memoryMiB": 8092,
  "onlyMarketplaceExtensions": false,
  "openUIOnStartupDisabled": false,
  "overrideProxyExclude": "*.docker.io,localhost,docker.com,api.segment.io",
  "overrideProxyHttp": "127.0.0.1:18080",
  "overrideProxyHttps": "127.0.0.1:18080",
  "proxyHttpMode": "manual",
  "settingsVersion": 17,
  "showExtensionsSystemContainers": false,
  "showKubernetesSystemContainers": false,
  "socksProxyPort": 0,
  "swapMiB": 1024,
  "tipLastId": 0,
  "tipLastViewedTime": 0,
  "updateAvailableTime": 1652772291871,
  "updatePopupAppearanceTime": 0,
  "updateSkippedBuild": "",
  "useCredentialHelper": true,
  "useNightlyBuildUpdates": false,
  "useVirtualizationFramework": false,
  "useVirtualizationFrameworkVirtioFS": false,
  "useVpnkit": true,
  "useWindowsContainers": false,
  "versionPack": "default",
  "vpnKitAllowedBindAddresses": "0.0.0.0",
  "vpnKitMTU": 1500,
  "vpnKitMaxConnections": 2000,
  "vpnKitMaxPortIdleTime": 300,
  "vpnKitTransparentProxy": true,
  "vpnkitCIDR": "192.168.65.0/24",
  "wslEngineEnabled": false
}
```
#### Scenario:
* private registry, only accessible via proxy (listening on localhost)
#### Behavior
* connecting to private registry works but pulling public images and logging in to docker.com via desktop app fails!

### Suggestion:
Implementing 3 different proxy Settings:
1. Docker Desktop Electron App needs to connect to the Internet
2. Containerd inside the VM needs to pull images from private or public registry via proxy
3. Containers need to connect to a $system via proxy

Additional: no_proxy needs to be honoured and available in all three settings

All these settings could be different from each other. Therefore they need to be configurable.

**Comment by laurazard** [comment]
Hi @bb-Ricardo, thank you for your report!

We are preparing a 4.8.2 release that addresses the regression regarding manual proxies overrides here:
- [RC mac Intel build](https://desktop-stage.docker.com/mac/main/amd64/79289/Docker.dmg)
- [RC mac ARM build](https://desktop-stage.docker.com/mac/main/arm64/79289/Docker.dmg) 
- [RC Windows build](https://desktop-stage.docker.com/win/main/amd64/79289/Docker%20Desktop%20Installer.exe) 
 
This should fix the issue you mentioned, and `no_proxy` should be honored. Regarding your feedback, we're currently collecting input, although having 3 different proxy settings isn't something we're currently considering.

However, if you'd like to let us know about your particular requirements asides from the regression in 4.8, please let us know here: https://github.com/docker/roadmap/issues/339

**Comment by bb-Ricardo** [comment]
Thank you for your feedback.

I know having three different proxy settings increases the complexity quite a bit. This also would confuse users who don't know what that all this means. But professionals which are using this app for application development in their company and paying a monthly fee for a subscription, should have the  possibility to define these settings.

**Comment by colceagus** [comment]
version 4.8.2 build 79419 didn't fix the issue. Please make at least ONE proxy config work properly. 
i'm pulling my hair not being able to pull or build images under corp VPN and proxy.

**Comment by laurazard** [comment]
I'm sorry to hear the build didn't fix your issue @colceagus. If you'd like, feel free to submit an issue of your own and upload diagnostics so we can take a look at what's not working.
