### ISSUE TITLE
Docker Desktop Starting infinite loop - 4.16.0 (95345)

### ISSUE THREAD

**Issue by ronjonesjr** [docker/for-mac#6673]
- [x ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: 22AC81B6-E1D7-47C2-A3BB-8A3F44543625/20230112184202

### Expected behavior
Docker Desktop should start without issue.

### Actual behavior
It loops forever displaying "Docker Desktop starting..."

### Information

  - macOS Version: macOS Monterey 12.6.2
  - Intel chip or Apple chip: Apple Chip
  - Docker Desktop Version: 4.16.0 (95345)

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[FAIL] DD0004: is the Docker engine running? Get "http://ipc/docker": dial unix lifecycle-server.sock: connect: no such file or directory
[2023-01-12T18:44:17.096275000Z][com.docker.diagnose][I] ipc.NewClient: e97c5efd-com.docker.diagnose -> lifecycle-server.sock VMDockerdAPI
[linuxkit/pkg/desktop-host-tools/pkg/client.NewClientForPath(...)
[	linuxkit/pkg/desktop-host-tools/pkg/client/client.go:63
[linuxkit/pkg/desktop-host-tools/pkg/client.NewClient({0x100a94a24, 0x13})
[	linuxkit/pkg/desktop-host-tools/pkg/client/client.go:57 +0x90
[common/pkg/diagkit/gather/diagnose.isDockerEngineRunning()
[	common/pkg/diagkit/gather/diagnose/dockerd.go:21 +0x28
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x10118f8e0)
[	common/pkg/diagkit/gather/diagnose/test.go:46 +0x40
[common/pkg/diagkit/gather/diagnose.Run.func1(0x10118f8e0)
[	common/pkg/diagkit/gather/diagnose/run.go:17 +0x40
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x3?, 0x10118f8e0)
[	common/pkg/diagkit/gather/diagnose/run.go:142 +0x80
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x2, 0x10118f8e0, 0x1400056f718)
[	common/pkg/diagkit/gather/diagnose/run.go:151 +0x88
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x10118f9e0, 0x1400056f718)
[	common/pkg/diagkit/gather/diagnose/run.go:148 +0x50
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x10118fc60, 0x1400056f718)
[	common/pkg/diagkit/gather/diagnose/run.go:148 +0x50
[common/pkg/diagkit/gather/diagnose.walkOnce(0x100c61500?, 0x1400036f890)
[	common/pkg/diagkit/gather/diagnose/run.go:137 +0x8c
[common/pkg/diagkit/gather/diagnose.Run(0x10118fc60, 0x39e95910?, {0x1400036fb08, 0x1, 0x1})
[	common/pkg/diagkit/gather/diagnose/run.go:16 +0x160
[main.checkCmd({0x14000134010?, 0x6?, 0x4?}, {0x0, 0x0})
[	common/cmd/com.docker.diagnose/main.go:138 +0xdc
[main.main()
[	common/cmd/com.docker.diagnose/main.go:102 +0x30c
[2023-01-12T18:44:17.096872000Z][com.docker.diagnose][I] (9b154ba5) e97c5efd-com.docker.diagnose C->S VMDockerdAPI GET /docker
[2023-01-12T18:44:17.097145000Z][com.docker.diagnose][W] (9b154ba5) e97c5efd-com.docker.diagnose C<-S NoResponse GET /docker (268.042µs): Get "http://ipc/docker": dial unix lifecycle-server.sock: connect: no such file or directory
[2023-01-12T18:44:17.097359000Z][com.docker.diagnose][I] (9b154ba5-1) e97c5efd-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-01-12T18:44:17.097593000Z][com.docker.diagnose][W] (9b154ba5-1) e97c5efd-com.docker.diagnose C<-S NoResponse GET /ping (231.875µs): Get "http://ipc/ping": dial unix lifecycle-server.sock: connect: no such file or directory
[2023-01-12T18:44:18.098141000Z][com.docker.diagnose][I] (9b154ba5-2) e97c5efd-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-01-12T18:44:18.099007000Z][com.docker.diagnose][W] (9b154ba5-2) e97c5efd-com.docker.diagnose C<-S NoResponse GET /ping (861µs): Get "http://ipc/ping": dial unix lifecycle-server.sock: connect: no such file or directory
[2023-01-12T18:44:19.099842000Z][com.docker.diagnose][I] (9b154ba5-3) e97c5efd-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-01-12T18:44:19.100236000Z][com.docker.diagnose][W] (9b154ba5-3) e97c5efd-com.docker.diagnose C<-S NoResponse GET /ping (392.375µs): Get "http://ipc/ping": dial unix lifecycle-server.sock: connect: no such file or directory
[2023-01-12T18:44:20.101217000Z][com.docker.diagnose][I] (9b154ba5-4) e97c5efd-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-01-12T18:44:20.102852000Z][com.docker.diagnose][W] (9b154ba5-4) e97c5efd-com.docker.diagnose C<-S NoResponse GET /ping (1.632291ms): Get "http://ipc/ping": dial unix lifecycle-server.sock: connect: no such file or directory
[2023-01-12T18:44:21.103579000Z][com.docker.diagnose][I] (9b154ba5-5) e97c5efd-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-01-12T18:44:21.104440000Z][com.docker.diagnose][W] (9b154ba5-5) e97c5efd-com.docker.diagnose C<-S NoResponse GET /ping (858.708µs): Get "http://ipc/ping": dial unix lifecycle-server.sock: connect: no such file or directory
[2023-01-12T18:44:22.105401000Z][com.docker.diagnose][I] (9b154ba5-6) e97c5efd-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-01-12T18:44:22.106267000Z][com.docker.diagnose][W] (9b154ba5-6) e97c5efd-com.docker.diagnose C<-S NoResponse GET /ping (909.792µs): Get "http://ipc/ping": dial unix lifecycle-server.sock: connect: no such file or directory
[2023-01-12T18:44:23.106951000Z][com.docker.diagnose][I] (9b154ba5-7) e97c5efd-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-01-12T18:44:23.107838000Z][com.docker.diagnose][W] (9b154ba5-7) e97c5efd-com.docker.diagnose C<-S NoResponse GET /ping (883.542µs): Get "http://ipc/ping": dial unix lifecycle-server.sock: connect: no such file or directory
[2023-01-12T18:44:24.108723000Z][com.docker.diagnose][I] (9b154ba5-8) e97c5efd-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-01-12T18:44:24.109620000Z][com.docker.diagnose][W] (9b154ba5-8) e97c5efd-com.docker.diagnose C<-S NoResponse GET /ping (891.084µs): Get "http://ipc/ping": dial unix lifecycle-server.sock: connect: no such file or directory

[PASS] DD0015: are the binary symlinks installed?
[FAIL] DD0031: does the Docker API work? Cannot connect to the Docker daemon at unix://docker.raw.sock. Is the docker daemon running?
[PASS] DD0013: is the $PATH ok?
Error response from daemon: dial unix docker.raw.sock: connect: no such file or directory
[FAIL] DD0003: is the Docker CLI working? exit status 1
[PASS] DD0038: is the connection to Docker working?
[PASS] DD0014: are the backend processes running?
[PASS] DD0007: is the backend responding?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[WARN] DD0004: is the Docker engine running? Get "http://ipc/docker": dial unix lifecycle-server.sock: connect: no such file or directory
[PASS] DD0015: are the binary symlinks installed?
[WARN] DD0031: does the Docker API work? Cannot connect to the Docker daemon at unix://docker.raw.sock. Is the docker daemon running?
[WARN] DD0032: do Docker networks overlap with host IPs? Cannot connect to the Docker daemon at unix://docker.raw.sock. Is the docker daemon running?

Please note the following 3 warnings:

1 : The check: is the Docker engine running?
    Produced the following warning: Get "http://ipc/docker": dial unix lifecycle-server.sock: connect: no such file or directory

The Docker engine manages all containers and images on the host. Check the dockerd.log to see why it failed to start.

2 : The check: does the Docker API work?
    Produced the following warning: Cannot connect to the Docker daemon at unix://docker.raw.sock. Is the docker daemon running?

If the Docker API is not available from the host then Docker Desktop will not work correctly.

3 : The check: do Docker networks overlap with host IPs?
    Produced the following warning: Cannot connect to the Docker daemon at unix://docker.raw.sock. Is the docker daemon running?

If the subnet used by a Docker network overlaps with an IP used by the host, then containers
won't be able to contact the overlapping IP addresses.

Try configuring the IP address range used by networks: in your docker-compose.yml.
See https://docs.docker.com/compose/compose-file/compose-file-v2/#ipv4_address-ipv6_address

Please investigate the following 1 issue:

1 : The test: is the Docker engine running?
    Failed with: Get "http://ipc/docker": dial unix lifecycle-server.sock: connect: no such file or directory

The Docker engine manages all containers and images on the host. Check the dockerd.log to see why it failed to start.

### Steps to reproduce the behavior

  1. Install Docker Desktop for mac (Apple Chip) from the website/interatively
  2. Start Docker Desktop for mac

**Comment by andreas-wittig** [comment]
same issue here on Windows 11

**Comment by dnguyen07** [comment]
Same here, just updated from 4.13 to 4.16 and "docker is starting" infinitely... :/

**Comment by andreas-wittig** [comment]
solved with update to 16.1

**Comment by brainz80** [comment]
I'm having same issues with 4.16.1 on Windows 10.

I've tried `wsl --shutdown` and shutting down Docker completely via Process Explorer. I tried switching my `wsl` default shell from `fish` to `bash`. Nothing seems to work.

**Comment by ronjonesjr** [comment]
This still happens on 14.6.0 and 14.6.1 for me.

**Comment by ronjonesjr** [comment]
I also tried upgrading to macOS Ventura 13.1 and Docker Desktop 4.16.1 still does not work.

**Comment by ronjonesjr** [comment]
Ok, I figured out that there's a BUG IN DOCKER somewhere before the osascript step WHEN you have a user directory on an external SSD drive.

When you have your home directory on a drive other than your boot drive and a symlink replacing your /users/username directory there's an issue somewhere in or before the osascript step.  When running Docker Desktop with a user directory on an external drive, the app never gets to that step.  

If instead I create an account on the same machine, and run the install with a user home drive on the boot drive, and I run Docker Desktop, I get to an osascript step which says, "Docker Desktop wants to create /var/run/docker.sock symlink; add startup task to symlink /Users/username/.docker/run/docker.sock to /var/run/docker.sock."

Anyone know how to officially report this bug?

**Comment by ronjonesjr** [comment]
Here's the original bug that I tried to workaround with a symlink.  If you do that, you get this infinite loop bug!

https://github.com/docker/for-mac/issues/6668

**Comment by applike-ss** [comment]
I have yesterday had someone with a long username (>15 characters) and creating a new user with a short username (4 characters) did look like it fixed the issue. However i have not verified this yet, it might simply work because it's a clean profile.

**Comment by applike-ss** [comment]
I have just checked it on my machine and created a user with the same name (41 characters) and it refused to start. I made sure to have stopped docker first on my original user. I'll create a new issue for this.
