### ISSUE TITLE
Docker for Mac crashes shortly after wake-up (macos Sierra)

### ISSUE THREAD

**Issue by jwegne** [docker/for-mac#819]
### Expected behavior

Docker should run without issues after host system wakes up from sleep.
### Actual behavior

Docker crashes silently and restarts - corrupting the cow2 image in the process.
### Information

Diagnostic ID: FCE91E11-5BA2-4819-BFE6-3933A1176824
- Full output of the diagnostics from "Diagnose & Feedback" in the menu
  Docker for Mac: version: 1.12.2-beta28 (71c4a00)
  OS X: version 10.12 (build: 16A323)
  logs: /tmp/FCE91E11-5BA2-4819-BFE6-3933A1176824/20161018-163456.tar.gz
  [OK]     docker-cli
  [OK]     virtualization kern.hv_support
  [OK]     menubar
  [OK]     moby-syslog
  [OK]     dns
  [OK]     disk
  [OK]     system
  [OK]     app
  [OK]     osxfs
  [OK]     virtualization VT-X
  [OK]     db
  [OK]     slirp
  [OK]     logs
  [OK]     env
  [OK]     vmnetd
  [OK]     moby-console
  [OK]     moby
  [OK]     driver.amd64-linux
- A reproducible case if this is a bug, Dockerfiles FTW
  N/A
- Page URL if this is a docs issue or the name of a man page
  N/A
### Steps to reproduce the behavior
1. Start Docker with fresh cow2 image (removing the old one).
2. Start screen process to login into Docker VM
3. Start some docker images (MongoDB, Tomcat, RabbitMQ)
4. Run some tests
5. Close the lid of the MacBook Pro
6. Go home
7. Open the MacBook Pro at home
8. Check if screen process to still runs - it does
9. One or two minutes later the screen process is dead, Docker silently restarted, cow2 image corrupted

Reproducible:
- 100%; every morning

**Comment by ijc25** [comment]
@jwegne thanks for your report, there have been various similar reports of what appears to be a C heap corruption which has been proving rather elusive but yours is the first report on beta28+ which finally gathered some more logging, which I was hoping would help pin point the issue. Sadly the stack traces here are of various threads falling victim to a prior corruption, which is not as helpful as I had hoped it would be.

Since you are able to reproduce at will would you be willing to try a few experiments for me, please?

Firstly, assuming you have installed Docker into `/Applications/Docker.app` could you please try running from a terminal with some `malloc` debugging options enabled, just open a terminal and type:
```
MallocErrorAbort=1 MallocScribble=1 MallocCheckHeapStart=1 MallocCheckHeapEach=1 MallocCheckHeapAbort=1 /Applications/Docker.app/Contents/MacOS/Docker
```
(this runs the app with some environment variables set which cause the malloc debugger to perform various checks and actions designed to expose problems, see `malloc(1)` if you are interested).

This should crash much closer to the source offer a diagnostics upload, if so please do the diagnostics upload. If it crashes without offering to upload a diagnostic then please do it manually by running:
```
/Applications/Docker.app/Contents/Resources/bin/docker-diagnose -u
```

One caveat: I've been using those debug options myself on our master branch (post beta28) and have discovered (and fixed) some issues (fixes will be in beta29, due in the next couple of days). It's possible that turning on those options will just make you trip over those same issues (it's even possible that your issue _is_ those issues) but I think seeing what happens for you with beta28 will still be useful. In the event you just trip over the existing issues perhaps you could try again with beta29 once it is available (assuming it hasn't been fixed!)?

**Comment by jwegne** [comment]
Hi @ijc25,

Thank you for your quick answer. I tried to run Docker with the debugging options enabled, but Docker does not start. Furthermore this command line causes my other programs to fail. After trying to start Docker several other applications (Firefox, Outlook) failed to start or behaved strange (could not type in Vivaldi).

This is the output of Docker with debugging options:
```
4demjwegne% MallocErrorAbort=1 MallocScribble=1 MallocCheckHeapStart=1 MallocCheckHeapEach=1 MallocCheckHeapAbort=1 /Applications/Docker.app/Contents/MacOS/Docker
Docker(2316,0x7fffcf9a73c0) malloc: enabling scribbling to detect mods to free blocks
Docker(2316,0x7fffcf9a73c0) malloc: enabling abort() on bad malloc or free
Docker(2316,0x7fffcf9a73c0) malloc: checks heap after 1th operation and each 1 operations
Docker(2316,0x7fffcf9a73c0) malloc: will abort on heap corruption
Docker(2316,0x7fffcf9a73c0) malloc: at szone_check counter=10000
Docker(2316,0x7fffcf9a73c0) malloc: at szone_check counter=20000
Docker(2316,0x7fffcf9a73c0) malloc: at szone_check counter=30000
Docker(2316,0x7fffcf9a73c0) malloc: at szone_check counter=40000
Docker(2316,0x7fffcf9a73c0) malloc: at szone_check counter=50000
Docker(2316,0x7fffcf9a73c0) malloc: at szone_check counter=60000
Docker(2316,0x7fffcf9a73c0) malloc: at szone_check counter=70000
INFO : KSCrash.m (323): -[KSCrash sendAllReportsWithCompletion:]: Sending 0 crash reports
sh(2405,0x7fffcf9a73c0) malloc: enabling scribbling to detect mods to free blocks
sh(2405,0x7fffcf9a73c0) malloc: enabling abort() on bad malloc or free
sh(2405,0x7fffcf9a73c0) malloc: checks heap after 1th operation and each 1 operations
sh(2405,0x7fffcf9a73c0) malloc: will abort on heap corruption
sysctl(2406,0x7fffcf9a73c0) malloc: enabling scribbling to detect mods to free blocks
sysctl(2406,0x7fffcf9a73c0) malloc: enabling abort() on bad malloc or free
sysctl(2406,0x7fffcf9a73c0) malloc: checks heap after 1th operation and each 1 operations
sysctl(2406,0x7fffcf9a73c0) malloc: will abort on heap corruption
grep(2407,0x7fffcf9a73c0) malloc: enabling scribbling to detect mods to free blocks
grep(2407,0x7fffcf9a73c0) malloc: enabling abort() on bad malloc or free
grep(2407,0x7fffcf9a73c0) malloc: checks heap after 1th operation and each 1 operations
grep(2407,0x7fffcf9a73c0) malloc: will abort on heap corruption
kern.hv_support: 1
sh(2408,0x7fffcf9a73c0) malloc: enabling scribbling to detect mods to free blocks
sh(2408,0x7fffcf9a73c0) malloc: enabling abort() on bad malloc or free
sh(2408,0x7fffcf9a73c0) malloc: checks heap after 1th operation and each 1 operations
sh(2408,0x7fffcf9a73c0) malloc: will abort on heap corruption
kextstat(2409,0x7fffcf9a73c0) malloc: enabling scribbling to detect mods to free blocks
kextstat(2409,0x7fffcf9a73c0) malloc: enabling abort() on bad malloc or free
kextstat(2409,0x7fffcf9a73c0) malloc: checks heap after 1th operation and each 1 operations
kextstat(2409,0x7fffcf9a73c0) malloc: will abort on heap corruption
grep(2410,0x7fffcf9a73c0) malloc: enabling scribbling to detect mods to free blocks
grep(2410,0x7fffcf9a73c0) malloc: enabling abort() on bad malloc or free
grep(2410,0x7fffcf9a73c0) malloc: checks heap after 1th operation and each 1 operations
grep(2410,0x7fffcf9a73c0) malloc: will abort on heap corruption
grep(2411,0x7fffcf9a73c0) malloc: enabling scribbling to detect mods to free blocks
grep(2411,0x7fffcf9a73c0) malloc: enabling abort() on bad malloc or free
grep(2411,0x7fffcf9a73c0) malloc: checks heap after 1th operation and each 1 operations
grep(2411,0x7fffcf9a73c0) malloc: will abort on heap corruption
grep(2412,0x7fffcf9a73c0) malloc: enabling scribbling to detect mods to free blocks
grep(2412,0x7fffcf9a73c0) malloc: enabling abort() on bad malloc or free
grep(2412,0x7fffcf9a73c0) malloc: checks heap after 1th operation and each 1 operations
grep(2412,0x7fffcf9a73c0) malloc: will abort on heap corruption
kextstat(2409,0x7fffcf9a73c0) malloc: at szone_check counter=10000
kextstat(2409,0x7fffcf9a73c0) malloc: at szone_check counter=20000
kextstat(2409,0x7fffcf9a73c0) malloc: at szone_check counter=30000
kextstat(2409,0x7fffcf9a73c0) malloc: at szone_check counter=40000
Docker(2316,0x7fffcf9a73c0) malloc: at szone_check counter=80000
Docker(2316,0x7fffcf9a73c0) malloc: at szone_check counter=90000
Docker(2316,0x7fffcf9a73c0) malloc: at szone_check counter=100000
Docker(2316,0x7fffcf9a73c0) malloc: at szone_check counter=110000
Docker(2316,0x70000b1c7000) malloc: at szone_check counter=120000
Docker(2316,0x7fffcf9a73c0) malloc: at szone_check counter=130000
Docker(2316,0x7fffcf9a73c0) malloc: at szone_check counter=140000
Docker(2316,0x7fffcf9a73c0) malloc: at szone_check counter=150000
com.docker.frontend(2609,0x7fffcf9a73c0) malloc: enabling scribbling to detect mods to free blocks
com.docker.frontend(2609,0x7fffcf9a73c0) malloc: enabling abort() on bad malloc or free
com.docker.frontend(2609,0x7fffcf9a73c0) malloc: checks heap after 1th operation and each 1 operations
com.docker.frontend(2609,0x7fffcf9a73c0) malloc: will abort on heap corruption
com.docker.frontend(2615,0x7fffcf9a73c0) malloc: enabling scribbling to detect mods to free blocks
com.docker.frontend(2615,0x7fffcf9a73c0) malloc: enabling abort() on bad malloc or free
com.docker.frontend(2615,0x7fffcf9a73c0) malloc: checks heap after 1th operation and each 1 operations
com.docker.frontend(2615,0x7fffcf9a73c0) malloc: will abort on heap corruption
time="2016-10-20T08:37:49+02:00" level=fatal msg="dial unix /Users/jwegne/Library/Containers/com.docker.docker/Data/s20: connect: connection refused" 
Docker(2316,0x70000b55c000) malloc: at szone_check counter=160000
´´´

**Comment by jwegne** [comment]
Not sure if this helps, but running the command a bit later crashed Docker while starting up.

Log:
```
4demjwegne% MallocErrorAbort=1 MallocScribble=1 MallocCheckHeapStart=1 MallocCheckHeapEach=1 MallocCheckHeapAbort=1 /Applications/Docker.app/Contents/MacOS/Docker
Docker(37981,0x7fffcf9a73c0) malloc: enabling scribbling to detect mods to free blocks
Docker(37981,0x7fffcf9a73c0) malloc: enabling abort() on bad malloc or free
Docker(37981,0x7fffcf9a73c0) malloc: checks heap after 1th operation and each 1 operations
Docker(37981,0x7fffcf9a73c0) malloc: will abort on heap corruption
Docker(37981,0x7fffcf9a73c0) malloc: at szone_check counter=10000
Docker(37981,0x70000c6de000) malloc: at szone_check counter=20000
Docker(37981,0x70000c6de000) malloc: at szone_check counter=30000
Docker(37981,0x7fffcf9a73c0) malloc: at szone_check counter=40000
Docker(37981,0x7fffcf9a73c0) malloc: at szone_check counter=50000
Docker(37981,0x7fffcf9a73c0) malloc: at szone_check counter=60000
ERROR: KSCrashState.c (238): _Bool kscrashstate_i_loadState(KSCrash_State *const, const char *const): /Users/jwegne/Library/Caches/KSCrashReports/Docker/Docker-CrashState.json, offset 87: Incomplete data
Docker(37981,0x7fffcf9a73c0) malloc: at szone_check counter=70000
INFO : KSCrash.m (323): -[KSCrash sendAllReportsWithCompletion:]: Sending 0 crash reports
sh(38084,0x7fffcf9a73c0) malloc: enabling scribbling to detect mods to free blocks
sh(38084,0x7fffcf9a73c0) malloc: enabling abort() on bad malloc or free
sh(38084,0x7fffcf9a73c0) malloc: checks heap after 1th operation and each 1 operations
sh(38084,0x7fffcf9a73c0) malloc: will abort on heap corruption
sysctl(38085,0x7fffcf9a73c0) malloc: enabling scribbling to detect mods to free blocks
sysctl(38085,0x7fffcf9a73c0) malloc: enabling abort() on bad malloc or free
sysctl(38085,0x7fffcf9a73c0) malloc: checks heap after 1th operation and each 1 operations
sysctl(38085,0x7fffcf9a73c0) malloc: will abort on heap corruption
grep(38086,0x7fffcf9a73c0) malloc: enabling scribbling to detect mods to free blocks
grep(38086,0x7fffcf9a73c0) malloc: enabling abort() on bad malloc or free
grep(38086,0x7fffcf9a73c0) malloc: checks heap after 1th operation and each 1 operations
grep(38086,0x7fffcf9a73c0) malloc: will abort on heap corruption
kern.hv_support: 1
sh(38087,0x7fffcf9a73c0) malloc: enabling scribbling to detect mods to free blocks
sh(38087,0x7fffcf9a73c0) malloc: enabling abort() on bad malloc or free
sh(38087,0x7fffcf9a73c0) malloc: checks heap after 1th operation and each 1 operations
sh(38087,0x7fffcf9a73c0) malloc: will abort on heap corruption
kextstat(38088,0x7fffcf9a73c0) malloc: enabling scribbling to detect mods to free blocks
kextstat(38088,0x7fffcf9a73c0) malloc: enabling abort() on bad malloc or free
kextstat(38088,0x7fffcf9a73c0) malloc: checks heap after 1th operation and each 1 operations
kextstat(38088,0x7fffcf9a73c0) malloc: will abort on heap corruption
grep(38089,0x7fffcf9a73c0) malloc: enabling scribbling to detect mods to free blocks
grep(38090,0x7fffcf9a73c0) malloc: enabling scribbling to detect mods to free blocks
grep(38089,0x7fffcf9a73c0) malloc: enabling abort() on bad malloc or free
grep(38089,0x7fffcf9a73c0) malloc: checks heap after 1th operation and each 1 operations
grep(38090,0x7fffcf9a73c0) malloc: enabling abort() on bad malloc or free
grep(38089,0x7fffcf9a73c0) malloc: will abort on heap corruption
grep(38090,0x7fffcf9a73c0) malloc: checks heap after 1th operation and each 1 operations
grep(38090,0x7fffcf9a73c0) malloc: will abort on heap corruption
grep(38091,0x7fffcf9a73c0) malloc: enabling scribbling to detect mods to free blocks
grep(38091,0x7fffcf9a73c0) malloc: enabling abort() on bad malloc or free
grep(38091,0x7fffcf9a73c0) malloc: checks heap after 1th operation and each 1 operations
grep(38091,0x7fffcf9a73c0) malloc: will abort on heap corruption
kextstat(38088,0x7fffcf9a73c0) malloc: at szone_check counter=10000
kextstat(38088,0x7fffcf9a73c0) malloc: at szone_check counter=20000
kextstat(38088,0x7fffcf9a73c0) malloc: at szone_check counter=30000
kextstat(38088,0x7fffcf9a73c0) malloc: at szone_check counter=40000
Docker(37981,0x7fffcf9a73c0) malloc: at szone_check counter=80000
Docker(37981,0x7fffcf9a73c0) malloc: at szone_check counter=90000
Docker(37981,0x7fffcf9a73c0) malloc: at szone_check counter=100000
Docker(37981,0x7fffcf9a73c0) malloc: at szone_check counter=110000
Docker(37981,0x7fffcf9a73c0) malloc: at szone_check counter=120000
Docker(37981,0x70000c867000) malloc: at szone_check counter=130000
Docker(37981,0x70000ca73000) malloc: at szone_check counter=140000
Docker(37981,0x7fffcf9a73c0) malloc: at szone_check counter=150000
com.docker.frontend(38272,0x7fffcf9a73c0) malloc: enabling scribbling to detect mods to free blocks
com.docker.frontend(38272,0x7fffcf9a73c0) malloc: enabling abort() on bad malloc or free
com.docker.frontend(38272,0x7fffcf9a73c0) malloc: checks heap after 1th operation and each 1 operations
com.docker.frontend(38272,0x7fffcf9a73c0) malloc: will abort on heap corruption
com.docker.frontend(38273,0x7fffcf9a73c0) malloc: enabling scribbling to detect mods to free blocks
com.docker.frontend(38273,0x7fffcf9a73c0) malloc: enabling abort() on bad malloc or free
com.docker.frontend(38273,0x7fffcf9a73c0) malloc: checks heap after 1th operation and each 1 operations
com.docker.frontend(38273,0x7fffcf9a73c0) malloc: will abort on heap corruption
time="2016-10-20T10:24:31+02:00" level=fatal msg="dial unix /Users/jwegne/Library/Containers/com.docker.docker/Data/s20: connect: connection refused" 
Docker(37981,0x70000cb79000) malloc: at szone_check counter=160000
INFO : KSCrashReport.c (2169): void kscrashreport_writeStandardReport(KSCrash_Context *const, const char *const): Writing crash report to /Users/jwegne/Library/Caches/KSCrashReports/Docker/Docker-CrashReport-6C24E818-E6E7-43A1-B21F-C04D4FF023C0.json
ERROR: KSMach.c (418): _Bool ksmach_resumeAllThreadsExcept(thread_t *, int): thread_resume (00007017): (ipc/send) invalid destination port
Docker(37981,0x7fffcf9a73c0) malloc: at szone_check counter=170000
com.docker.frontend(38312,0x7fffcf9a73c0) malloc: enabling scribbling to detect mods to free blocks
com.docker.frontend(38312,0x7fffcf9a73c0) malloc: enabling abort() on bad malloc or free
com.docker.frontend(38312,0x7fffcf9a73c0) malloc: checks heap after 1th operation and each 1 operations
com.docker.frontend(38312,0x7fffcf9a73c0) malloc: will abort on heap corruption
com.docker.frontend(38313,0x7fffcf9a73c0) malloc: enabling scribbling to detect mods to free blocks
com.docker.frontend(38313,0x7fffcf9a73c0) malloc: enabling abort() on bad malloc or free
com.docker.frontend(38313,0x7fffcf9a73c0) malloc: checks heap after 1th operation and each 1 operations
com.docker.frontend(38313,0x7fffcf9a73c0) malloc: will abort on heap corruption
zsh: segmentation fault  MallocErrorAbort=1 MallocScribble=1 MallocCheckHeapStart=1 MallocCheckHeapEac
time="2016-10-20T10:24:34+02:00" level=fatal msg="unexpected EOF" 
```

```
4demjwegne% /Applications/Docker.app/Contents/Resources/bin/docker-diagnose -u
OS X: version 10.12 (build: 16A323)
Docker.app: version: 1.12.2-beta28 (71c4a00)
Local time: Do 20 Okt 2016 10:25:58 CEST
UTC:        Do 20 Okt 2016 08:25:58 UTC
Timestamp:  20161020-102558
Running diagnostic tests:
[OK]      docker-cli
[OK]      Moby booted
[OK]      driver.amd64-linux
[OK]      vmnetd
[ERROR]   osxfs            com.docker.osxfs is not running
[OK]      db
[OK]      slirp
[OK]      disk
[OK]      menubar
[OK]      environment
[OK]      Docker
[OK]      VT-x
[OK]      kern.hv_support
Most specific failure is: com.docker.osxfs is not running
Docker logs are being collected into /tmp/FCE91E11-5BA2-4819-BFE6-3933A1176824/20161020-102558.tar.gz
Your unique id is: FCE91E11-5BA2-4819-BFE6-3933A1176824
Please quote this in all correspondence.
```

**Comment by ijc25** [comment]
> Furthermore this command line causes my other programs to fail. After trying to start Docker several other applications (Firefox, Outlook) failed to start or behaved strange (could not type in Vivaldi).

Sorry about this, this wasn't what I expected at all, the command line I gave should have set those environment variables only for the process being spawned by that line so there should have been no impact on any other process.

Did you manage to sort things out? Since I've no idea how/why this would have happened I'm not sure what to suggest -- maybe just killing the particular terminal window you ran the command in, otherwise I hope a reboot would sort it?

I'll take a look at your other logs etc now, thanks.

**Comment by jwegne** [comment]
Yes, I was able to sort things out. Stopping the command line fixed the issue and the other programs started/worked fine. I ran the command in a tmux session; perhaps this caused the side effects. I will try a standalone bash session.

**Comment by ijc25** [comment]
@jwegne it looks like your `/Applications/Docker.app/Contents/Resources/bin/docker-diagnose` is not the version which came with beta28 (it looks like it is maybe the one from around beta26 or maybe stable). Unfortunately the logs I need were only collected starting with beta28.

Did you install beta28 in a different path other than `/Applications/Docker.app` perhaps? Please could you try and locate the `docker-diagnose` binary under wherever you installed beta28 and run that (with the `-u` option).

If you could also take a look in `$HOME/Library//Logs/DiagnosticReports/` for files named `com.docker.*.crash` which have date/time corresponding to the tests you ran those would be helpful too.

Thanks,Ian.

**Comment by jwegne** [comment]
[Docker_2016-10-20-102438_4demjwegne.crash.txt](https://github.com/docker/for-mac/files/541323/Docker_2016-10-20-102438_4demjwegne.crash.txt)

The crash report is uploaded. I installed the stable version and later updated to beta 28. It seems that the docker-diagnose was not correctly replaced. I will remove my docker installation and install beta 28 again.

**Comment by ijc25** [comment]
@jwegne thanks! Could you also please try the same command with all the `Malloc*` stuff but omitting the `MallocScribble=1` and upload the logs for that too.

BTW, you can also (if you want) add `MallocLogFile=$HOME/malloc.log` to the command to save all that stuff to a file -- which might be easier than cut and paste.

**Comment by jwegne** [comment]
@ijc25 Is it normal that Docker will start up very, very, very slowly with debugging options? I started it 30 Minutes ago, and it still not has been started.

**Comment by ijc25** [comment]
It's definitely expected to be slower but 30mins seems too slow, perhaps something has crashed due to the options. Probably best to drop the `MallocScript=1` option and just go with the rest.

**Comment by jwegne** [comment]
This run was without MallocScript/MallocScribble. That is the command i ran:
```
MallocErrorAbort=1 MallocCheckHeapStart=1 MallocCheckHeapEach=1 MallocCheckHeapAbort=1 MallocLogFile=$HOME/malloc.log /Applications/Docker.app/Contents/MacOS/Docker
```

I see lines like this in the log file:
```
Docker(17178,0x7fffa76853c0) malloc: at szone_check counter=10000
...
Docker(17178,0x700007b38000) malloc: at szone_check counter=470000
```

The counter goes quickly to 400000, but after that it takes several minutes for the next line to appear.

**Comment by ijc25** [comment]
Sorry, I did mean `MallocScribble` as you guessed, AFAIK `MallocScript` isn't a thing.

For me things seem to work tolerably without `MallocScribble`. You might also find that killing it and restarting it (maybe a few times) eventually makes progress.

At this point though I think I'm leaning towards waiting for beta29 to rule out the issues which are fixed there.

**Comment by jwegne** [comment]
The debugging options are not the issue. Even without the debugging options Docker will not start. I cleanly de-installed Docker, restarted, installed stable, but Docker hangs after showing the popup (Nice whaling with you - or something similar).

Might be an issue with my MacOS X installation. It seems I have to reinstall it.

**Comment by ijc25** [comment]
(I somehow missed the mail notification of the last comment, sorry)

I guess that is unrelated to the post-sleep crash issue. Best bet is probably to open a new ticket with a fresh diagnostic taken in (or right after) the hanging state.

**Comment by jwegne** [comment]
It seems that my macOS installation was broken. With a freshly installed macOS Docker starts up just fine. Also, I did not encounter any crashes after waking up my Mac. But the Docker.cow2 images still gets corrupted when I restart or shutdown Docker.

Still, I will try to reproduce the crashes the next few day, but I think they were also related to my broken macOS.

**Comment by samoht** [comment]
We have switched to `overlay2` in Beta29, that you need to enable to reseting to factory defaults (see the changelog). Can you please try to see if that fixes your problem? We know that `aufs` get corrupted easily on hard shudown (which could happens when you kill the VM running inside Docker.app) and we hope that `overlay2` will fix these problems.

**Comment by jwegne** [comment]
Thanks, I switched to overlay2.

But after (clean) shutdown of Docker I get following issues when checking the cow2 image:

```
4demjwegne:~ jwegne$ qemu-img check ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 

ERROR cluster 0 refcount=0 reference=1
ERROR cluster 1 refcount=0 reference=1
ERROR cluster 2 refcount=0 reference=1
ERROR cluster 3 refcount=0 reference=1
ERROR cluster 4 refcount=0 reference=1
ERROR cluster 5 refcount=0 reference=1
ERROR cluster 6 refcount=0 reference=1
ERROR cluster 7 refcount=0 reference=1
ERROR cluster 8 refcount=0 reference=1
ERROR cluster 9 refcount=0 reference=1
...
ERROR cluster 3242 refcount=0 reference=1
ERROR cluster 3243 refcount=0 reference=1
ERROR cluster 3244 refcount=0 reference=1
ERROR cluster 3245 refcount=0 reference=1
ERROR cluster 3246 refcount=0 reference=1
ERROR OFLAG_COPIED L2 cluster: l1_index=0 l1_entry=8000000000030000 refcount=0
ERROR OFLAG_COPIED data cluster: l2_entry=8000000000040000 refcount=0
ERROR OFLAG_COPIED data cluster: l2_entry=8000000000050000 refcount=0
ERROR OFLAG_COPIED L2 cluster: l1_index=8 l1_entry=8000000000060000 refcount=0
ERROR OFLAG_COPIED data cluster: l2_entry=8000000000070000 refcount=0
ERROR OFLAG_COPIED data cluster: l2_entry=8000000000080000 refcount=0
ERROR OFLAG_COPIED data cluster: l2_entry=8000000000090000 refcount=0
ERROR OFLAG_COPIED data cluster: l2_entry=80000000000a0000 refcount=0
...
ERROR OFLAG_COPIED data cluster: l2_entry=800000000b360000 refcount=0
ERROR OFLAG_COPIED data cluster: l2_entry=800000000b4e0000 refcount=0
ERROR OFLAG_COPIED data cluster: l2_entry=800000000b370000 refcount=0
ERROR OFLAG_COPIED data cluster: l2_entry=800000000b4a0000 refcount=0
ERROR OFLAG_COPIED data cluster: l2_entry=800000000b4b0000 refcount=0
ERROR OFLAG_COPIED data cluster: l2_entry=800000000b4c0000 refcount=0
ERROR OFLAG_COPIED L2 cluster: l1_index=124 l1_entry=8000000008940000 refcount=0
ERROR OFLAG_COPIED data cluster: l2_entry=8000000008950000 refcount=0
ERROR OFLAG_COPIED L2 cluster: l1_index=127 l1_entry=8000000008960000 refcount=0
ERROR OFLAG_COPIED data cluster: l2_entry=8000000008970000 refcount=0

6491 errors were found on the image.
Data may be corrupted, or further writes to the image may corrupt it.
3207/1048576 = 0.31% allocated, 0.72% fragmented, 0.00% compressed clusters
Image end offset: 212795392
```

Steps to reproduce:
1. Remove old Docker.cow2
2. Start Docker
3. Quit Docker
4. Check Docker.cow2

**Comment by justincormack** [comment]
`qemu-img` errors are unrelated to the filesystem on the image.

@djs55 are these errors a problem?

@jwegne can you update to the beta 29.2 that is out now and see if there is any difference?

**Comment by jwegne** [comment]
@justincormack, I re-tested with beta 29.2. `qemu-img` still shows errors, but the filesystem seems to be fine. No ext4 errors so far.

**Comment by ijc25** [comment]
Are there any remaining issues here? Seems like the original crash has been resolved either by the fixes made in beta29 or by the OSX reinstall (or at least has become unreproducible somehow) and the fs corruption seems ok with beta29.2 (AIUI `qemu-img check` is prone to false positives, or at least it being noisy is not necessarily an indication of qcow2 corruption).

I think I'll close this ticket. If the original malloc crash reoccurs please do a diagnostics upload and ping here to reopen, if the filesystem issues reoccur I think it would be best to start a fresh ticket (with a diagnostics bundle too) for that.

**Comment by jwegne** [comment]
Everything seems to be stable now. I will create another issue if I encounter other crashes.

Thank you very much for your help.
