### ISSUE TITLE
Docker networking components failed on Mac OS 10.11.6

### ISSUE THREAD

**Issue by msimon** [docker/for-mac#930]
### Actual behavior
Docker does not start. Ask for my admin password then return:
"Fatal Error"
"Communication with networking components failed"

### Information

- Previous version stop to be able to start (the docker icon was present, but stuck on starting). I didn't have time to investigate
- Installed the latest version this morning, and now crash right after I enter my admin password.

  Docker for Mac: version: 1.12.3 (583d1b8)
OS X: version 10.11.6 (build: 15G1108)
logs: /tmp/3D851B4A-3496-44AB-8D0C-56C9CD86C06B/20161110-130339.tar.gz
failure: com.docker.slirp is not running
[ERROR]  vmnetd
         Connection refused (ECONNREFUSED) connecting to /var/tmp/com.docker.vmnetd.socket: check if service is running
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     dns
[ERROR]  driver.amd64-linux
         com.docker.driver.amd64-linux -db is not running
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/masimon/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[OK]     env
[OK]     virtualization kern.hv_support
[ERROR]  slirp
         Connection refused (ECONNREFUSED) connecting to /Users/masimon/Library/Containers/com.docker.docker/Data/s51: check if service is running
         com.docker.slirp is not running
         slirp check failed with: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     moby-console
[OK]     logs
[ERROR]  docker-cli
         /var/run/docker.sock does not exist
         Unexpected error (No such file or directory) connecting to /var/run/docker.sock
         Connection refused (ECONNREFUSED) connecting to /Users/masimon/Library/Containers/com.docker.docker/Data/s60: check if service is running
         docker ps failed
[OK]     menubar
[OK]     disk
Failure: Could not upload diagnostic data to remote server (docker-diagnose exit code is 1)

Diagnostic ID: 3D851B4A-3496-44AB-8D0C-56C9CD86C06B

### Steps to reproduce the behavior
Start docker

Thanks

**Comment by ijc25** [comment]
Detected symptom of problem 'vmnetd-comm-failure' in 3D851B4A-3496-44AB-8D0C-56C9CD86C06B/20161110-110207.

The UI failed to communicate with the networking helper process.

Try the following steps:
- stop Docker for Mac
- delete the file `/Library/PrivilegedHelperTools/com.docker.vmnetd`
- start Docker for Mac

Hopefully this will (re-)install the networking helper process properly. Please re-open this issue if your problem persists.

May be related to docker/for-mac#61

Your logs also show signs of aufs corruption, possibly related to the earlier problem being stuck on starting (which looks to have been caused by a series of crashes which are fixed in 1.12.3). If that issue persists once the communication with the networking components is sorted then a factory reset should resolve it for you, note that this will destroy any existing containers.

**Comment by msimon** [comment]
Hey @ijc25,

I deleted /Library/PrivilegedHelperTools/com.docker.vmnetd. The issue still persisted so I deleted `~/Library/Containers/com.docker.docker` to do a factory reset.

Now the issue still persist, but on top of this the diagnostic return: `failure: Optional("diagnostic: response is not valid JSON")`

Any idea ?

Thanks

**Comment by kmalakoff** [comment]
I've been running into the same problem with the same error `response is not valid JSON`. 

I spent a couple of hours yesterday trying everything I could find in these issues and through Google search including the steps around vmnetd (eg. deleting, restarting the service, changing permissions, etc), but no luck. I had to revert to the legacy approach (eg. virtualbox and docker toolbox) to work around this. 

I can help troubleshoot on my machine if you need, but I think this issue should remain open.

**Comment by msimon** [comment]
@kmalakoff same for me, went back to the toolbox.

**Comment by ijc25** [comment]
@msimon / @kmalakoff are either of you able to upload a diagnostic manually by running `~/Library/Group Containers/group.com.docker/bin/docker-diagnose -u` from a terminal?

Performing a factory reset might also help here (ideally after trying the manual diagnostic).

**Comment by armandofelipe1992** [comment]
Now the issue still persist, but on top of this the diagnostic return: failure: Optional("diagnostic: response is not valid JSON")

Any idea ?

Thanks

**Comment by djs55** [comment]
Sorry it's still not working. @armandofelipe1992 could you try running the command:
```
/Applications/Docker.app/Contents/Resources/bin/docker-diagnose --json
```
and post the output? I'd like to see whether there's an obvious problem with the .json.

It's also worth trying again with the latest beta (33.1) to see if it behaves differently.

Thanks!

**Comment by wingpang-gz** [comment]
Error exec: uuidgen > "/Users/wingpang/Library/Containers/com.docker.docker/Data/user.id": exit 1
Fatal error: exception (Failure
  "exec: uuidgen > \"/Users/wingpang/Library/Containers/com.docker.docker/Data/u

**Comment by dsheets** [comment]
@wingpang-gz could you please open a new issue with more information about the `docker-diagnose` error? Specifically, it would be great to know the output of `uuidgen; echo $?` and `which uuidgen; echo $?`.

**Comment by nmarley** [comment]
@dsheets The problem isn't with `uuidgen`, it's that the `$HOME/Library/Containers/com.docker.docker` directory (or some other element of the path above) is gone, so the shell can't write to a file there.

```$ uuidgen > "/Users/nmarley/Library/Containers/com.docker.docker/Data/user.id"
-bash: /Users/nmarley/Library/Containers/com.docker.docker/Data/user.id: No such file or directory
$ echo $?
1```

**Comment by samoht** [comment]
@msimon it seems that you installed Docker for Mac in a different location that the one recommend:

```
<Notice>: <rdar://problem/11489077> A sandboxed application with pid 910,
"DockerHelper" checked in with appleeventsd, but its code signature could not be read and validated by appleeventsd, and so it cannot receive AppleEvents t
argeted by name, bundle id, or signature. Install the application in /Applications/ or some other world readable location to resolve this issue. Error=ERRO
R: #100013  { "NSDescription"="SecCodeCopySigningInformation() returned 100013, -." }  (handleMessage()/appleEventsD.cp #2098)
```

We improved the installer/launcher quite a lot since last November, so hopefully this kind of error should not happen anymore.

@nmarley is your `Docker.app` in your application folder? If not can you try to move it there and run the diagnostic command from there? Do you have the same issue as @wingpang-gz and @msimon? Thanks!

**Comment by samoht** [comment]
I am going to close that issue for now on, @wingpang-gz and @msimon you are very welcome to open a new issue with a fresh diagnostic ID.

**Comment by samukce** [comment]
`{
"os": "macOS: version 10.11.6 (build: 15G1217)",
"app": "version: 1.13.1 (94675c5a7)",
"id": "57C46EB8-5BBC-49E3-AD2B-360F85CD76D0",
"logs": "/tmp/57C46EB8-5BBC-49E3-AD2B-360F85CD76D0/20170223-161619.tar.gz",
"failure": "com.docker.slirp is not running",
"tests": {
    "docker-cli": {
      "success": false,
      "message": [
        "Connection refused (ECONNREFUSED) connecting to /var/run/docker.sock: check if service is running",
        "Connection refused (ECONNREFUSED) connecting to /Users/spereira/Library/Containers/com.docker.docker/Data/s60: check if service is running",
        "docker ps failed"
      ]
    },
    "moby": {
      "success": false,
      "message": [
        "/Users/spereira/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist"
      ]
    },
    "driver.amd64-linux": {
      "success": false,
      "message": [
        "com.docker.driver.amd64-linux -db is not running"
      ]
    },
    "vmnetd": {
      "success": true,
      "message": []
    },
    "osxfs": {
      "success": false,
      "message": [
        "com.docker.osxfs is not running"
      ]
    },
    "db": {
      "success": false,
      "message": [
        "Connection refused (ECONNREFUSED) connecting to /Users/spereira/Library/Containers/com.docker.docker/Data/s40: check if service is running",
        "com.docker.db is not running"
      ]
    },
    "slirp": {
      "success": false,
      "message": [
        "Unexpected error ((Failure\n  \"Error connecting socket to 9p endpoint unix:/Users/spereira/Library/Containers/com.docker.docker/Data/s51: Unix.Unix_error(Unix.ECONNREFUSED, \\\"connect\\\", \\\"\\\")\")) connecting to /Users/spereira/Library/Containers/com.docker.docker/Data/s51",
        "com.docker.slirp is not running",
        "slirp check failed with: (Failure\n  \"Error connecting socket to 9p endpoint unix:/Users/spereira/Library/Containers/com.docker.docker/Data/s52: Unix.Unix_error(Unix.ECONNREFUSED, \\\"connect\\\", \\\"\\\")\")"
      ]
    },
    "dns": {
      "success": true,
      "message": []
    },
    "disk": {
      "success": true,
      "message": []
    },
    "menubar": {
      "success": true,
      "message": []
    },
    "env": {
      "success": true,
      "message": []
    },
    "app": {
      "success": true,
      "message": []
    },
    "virtualization VT-X": {
      "success": true,
      "message": []
    },
    "virtualization kern.hv_support": {
      "success": true,
      "message": []
    },
    "logs": {
      "success": true,
      "message": []
    },
    "app": {
      "success": true,
      "message": []
    },
    "moby-console": {
      "success": true,
      "message": []
    },
    "moby-syslog": {
      "success": true,
      "message": []
    },
    "moby": {
      "success": false,
      "message": [
        "moby check failed with: (Failure\n  \"exec: echo \\\"00000003.0000f3a6\\\" | nc -U /Users/spereira/Library/Containers/com.docker.docker/Data/@connect > /tmp/57C46EB8-5BBC-49E3-AD2B-360F85CD76D0/20170223-161619/diagnostics.tar: exit 1\")"
      ]
    },
    "system": {
      "success": true,
      "message": []
    }
  }
}`

**Comment by hmottestad** [comment]
Im getting a very similar issue. Can't even generate a diagnostics ID. All I get is: `failure: Optional("diagnostic: response is not valid JSON")`

Networking works fine for a a few hours, up to 24. After that I can't contact the containers with open ports out.

**Comment by hmottestad** [comment]
My docker info: 

```
Containers: 13
 Running: 11
 Paused: 0
 Stopped: 2
Images: 152
Server Version: 17.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 223
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.27-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 5.818 GiB
Name: moby
ID: 3XDB:XCIY:MRE4:S6QX:3NXZ:LX5G:UMJ4:42YX:LNTL:LX5D:L7ED:W74J
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 96
 Goroutines: 85
 System Time: 2017-06-12T20:56:27.415952795Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Comment by hmottestad** [comment]
My log is system log is full of this: 

```
Jun 12 22:57:21 mini Docker[4792]: exceeded maximum number of forwarded connections (900)
Jun 12 22:57:21 mini Docker[4792]: PPP.listen callback caught Hostnet.Host_uwt.Sockets.Too_many_connections
Jun 12 22:57:51 mini Docker[4792]: exceeded maximum number of forwarded connections (900)
Jun 12 22:57:51 mini Docker[4792]: PPP.listen callback caught Hostnet.Host_uwt.Sockets.Too_many_connections
Jun 12 22:58:21 mini Docker[4792]: exceeded maximum number of forwarded connections (900)
Jun 12 22:58:21 mini Docker[4792]: PPP.listen callback caught Hostnet.Host_uwt.Sockets.Too_many_connections
```
